### ISSUE TITLE
A test is failing in my environment

### ISSUE THREAD

**Issue by yaelbh** [Qiskit/qiskit-aer#1018]
Running the tests, I get:
```
======================================================================
ERROR: test.benchmark (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test.benchmark
Traceback (most recent call last):
  File "/opt/anaconda3/envs/YaelEnv/lib/python3.6/unittest/loader.py", line 462, in _find_test_path
    package = self._get_module_from_name(name)
  File "/opt/anaconda3/envs/YaelEnv/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/yaelbh/work/aer/RGates/test/benchmark/__init__.py", line 1, in <module>
    from .simulator_benchmark import SimulatorBenchmarkSuite
  File "/home/yaelbh/work/aer/RGates/test/benchmark/simulator_benchmark.py", line 22, in <module>
    from benchmark.circuit_library_circuits import CircuitLibraryCircuits
ModuleNotFoundError: No module named 'benchmark'
```

`pip install -r requirements-dev.txt` didn't help.

**Comment by mtreinish** [comment]
This is an issue with your test command. The discovery path for python tests should be `test/terra` the python code in `test/benchmarks` are not unittest code. What command are you using to running tests? (both using tox and stestr directly should work fine, but if you're manually invoking unittest run or some other runner you're probably not setting the discovery path correctly)

**Comment by yaelbh** [comment]
Thanks @mtreinish, indeed I'm using `unittest`.
