### ISSUE TITLE
 qiskit-aer-gpu install failed on Linux

### ISSUE THREAD

**Issue by Z-Y00** [Qiskit/qiskit-aer#1085]
### Informations

- **Qiskit Aer version**: latest
- **Python version**: Python 3.9.0
- **Operating system**: Linux

### What is the current behavior?

 pip install  qiskit-aer-gpu -v
```
ERROR: Could not find a version that satisfies the requirement qiskit-aer-gpu
ERROR: No matching distribution found for qiskit-aer-gpu
Exception information:
Traceback (most recent call last):
  File "/home/rgy/bin/miniconda2/envs/qubit/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 171, in _merge_into_criterion
    crit = self.state.criteria[name]
KeyError: 'qiskit-aer-gpu'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rgy/bin/miniconda2/envs/qubit/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 310, in resolve
    name, crit = self._merge_into_criterion(r, parent=None)
  File "/home/rgy/bin/miniconda2/envs/qubit/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _merge_into_criterion
    crit = Criterion.from_requirement(self._p, requirement, parent)
  File "/home/rgy/bin/miniconda2/envs/qubit/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 83, in from_requirement
    raise RequirementsConflicted(criterion)
pip._vendor.resolvelib.resolvers.RequirementsConflicted: Requirements conflict: SpecifierRequirement('qiskit-aer-gpu')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rgy/bin/miniconda2/envs/qubit/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 121, in resolve
    self._result = resolver.resolve(
  File "/home/rgy/bin/miniconda2/envs/qubit/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 445, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/rgy/bin/miniconda2/envs/qubit/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 312, in resolve
    raise ResolutionImpossible(e.criterion.information)
pip._vendor.resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=SpecifierRequirement('qiskit-aer-gpu'), parent=None)]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rgy/bin/miniconda2/envs/qubit/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 224, in _main
    status = self.run(options, args)
  File "/home/rgy/bin/miniconda2/envs/qubit/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 180, in wrapper
    return func(self, options, args)
  File "/home/rgy/bin/miniconda2/envs/qubit/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 320, in run
    requirement_set = resolver.resolve(
  File "/home/rgy/bin/miniconda2/envs/qubit/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 127, in resolve
    six.raise_from(error, e)
  File "<string>", line 3, in raise_from
pip._internal.exceptions.DistributionNotFound: No matching distribution found for qiskit-aer-gpu
Removed build tracker: '/tmp/pip-req-tracker-nga8ijza'

```

### Steps to reproduce the problem

I created a new conda env, and typed ``` pip install  qiskit-aer-gpu -v```

### What is the expected behavior?

I think it should works.

### Suggested solutions

None

**Comment by Z-Y00** [comment]
I think I got the reason, I have a higher python version that  qiskit-aer-gpu support

**Comment by mysterymeth** [comment]
Just to confirm, I got the same error with python 9.10 I needed to go to 9.8 to install with pipenv
