### ISSUE TITLE
reset is not in the set of basis gates

### ISSUE THREAD

**Issue by yaelbh** [Qiskit/qiskit-aer#1092]
I wonder why `reset` is missing from the list of basis gates for all the simulation methods. At the same time, the sister instruction `initialize` must be (and is indeed) in the list of basis gates, in order to operate.

My questions:
1. What is the mechanism, in the code, that makes `reset` special?
2. Does it make sense to have this difference between `reset` and `initialize` ?

Here is code to demonstrate the point:
```
from qiskit import QuantumCircuit, transpile
from qiskit.providers.aer import QasmSimulator

sim = QasmSimulator()

circ = QuantumCircuit(1)
circ.initialize([0, 1], 0)
circ.reset(0)

transpile(circ, sim, optimization_level=0, basis_gates=['initialize'])
print('ok when reset is missing from the list of basis gates')
transpile(circ, sim, optimization_level=0, basis_gates=['reset'])
print('ok when initialize is missing from the list of basis gates')
```

And the output:
ok when reset is missing from the list of basis gates
Traceback (most recent call last):
  File "reset_versus_initialize.py", line 12, in <module>
    transpile(circ, sim, optimization_level=0, basis_gates=['reset'])
  File "/opt/anaconda3/envs/YaelEnv/lib/python3.8/site-packages/qiskit/compiler/transpile.py", line 243, in transpile
    circuits = parallel_map(_transpile_circuit, list(zip(circuits, transpile_args)))
  File "/opt/anaconda3/envs/YaelEnv/lib/python3.8/site-packages/qiskit/tools/parallel.py", line 106, in parallel_map
    return [task(values[0], *task_args, **task_kwargs)]
  File "/opt/anaconda3/envs/YaelEnv/lib/python3.8/site-packages/qiskit/compiler/transpile.py", line 326, in _transpile_circuit
    result = pass_manager.run(circuit, callback=transpile_config['callback'],
  File "/opt/anaconda3/envs/YaelEnv/lib/python3.8/site-packages/qiskit/transpiler/passmanager.py", line 225, in run
    return self._run_single_circuit(circuits, output_name, callback)
  File "/opt/anaconda3/envs/YaelEnv/lib/python3.8/site-packages/qiskit/transpiler/passmanager.py", line 288, in _run_single_circuit
    result = running_passmanager.run(circuit, output_name=output_name, callback=callback)
  File "/opt/anaconda3/envs/YaelEnv/lib/python3.8/site-packages/qiskit/transpiler/runningpassmanager.py", line 113, in run
    dag = self._do_pass(pass_, dag, passset.options)
  File "/opt/anaconda3/envs/YaelEnv/lib/python3.8/site-packages/qiskit/transpiler/runningpassmanager.py", line 144, in _do_pass
    dag = self._run_this_pass(pass_, dag)
  File "/opt/anaconda3/envs/YaelEnv/lib/python3.8/site-packages/qiskit/transpiler/runningpassmanager.py", line 156, in _run_this_pass
    new_dag = pass_.run(dag)
  File "/opt/anaconda3/envs/YaelEnv/lib/python3.8/site-packages/qiskit/transpiler/passes/basis/basis_translator.py", line 107, in run
    raise TranspilerError(
qiskit.transpiler.exceptions.TranspilerError: "Unable to map source basis {('reset', 1), ('ry', 1)} to target basis {'reset', 'barrier', 'snapshot', 'delay', 'measure'} over library <qiskit.circuit.equivalence.EquivalenceLibrary object at 0x7fc985b112e0>."
```

**Comment by chriseclectic** [comment]
I think this is more a terra issue. I believe the transpiler/unroller has special handling for barrier, reset, measure. Every other instruction is treated like a "gate" and checked in basis_gates (including non-gate instructions like kraus, snapshot, initialize etc)

**Comment by yaelbh** [comment]
Thanks @chriseclectic
