### ISSUE TITLE
CI failed after terra-5701 is merged

### ISSUE THREAD

**Issue by hhorii** [Qiskit/qiskit-aer#1148]
### Informations

- **Qiskit Aer version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?

Since https://github.com/Qiskit/qiskit-terra/pull/5701 is merged into Terra, CI fails.

```
$ python -m unittest test.terra.backends.test_qasm_simulator.TestQasmSimulator.test_gate_density_matrix_075
E
======================================================================
ERROR: test_gate_density_matrix_075 (test.terra.backends.test_qasm_simulator.TestQasmSimulator)
Test standard gate simulation test.
----------------------------------------------------------------------
testtools.testresult.real._StringException: Traceback (most recent call last):
  File "/lib/python3.9/site-packages/ddt.py", line 182, in wrapper
    return func(self, *args, **kwargs)
  File "qiskit-aer/test/terra/backends/qasm_simulator/qasm_standard_gates.py", line 178, in test_gate_density_matrix
    result = execute(circuit, backend, shots=1, basis_gates=basis_gates,
  File "/lib/python3.9/site-packages/qiskit/execute_function.py", line 252, in execute
    experiments = transpile(experiments,
  File "/lib/python3.9/site-packages/qiskit/compiler/transpiler.py", line 242, in transpile
    circuits = parallel_map(_transpile_circuit, list(zip(circuits, transpile_args)))
  File "/python3.9/site-packages/qiskit/tools/parallel.py", line 112, in parallel_map
    return [task(values[0], *task_args, **task_kwargs)]
  File "/lib/python3.9/site-packages/qiskit/compiler/transpiler.py", line 325, in _transpile_circuit
    result = pass_manager.run(circuit, callback=transpile_config['callback'],
  File "/lib/python3.9/site-packages/qiskit/transpiler/passmanager.py", line 215, in run
    return self._run_single_circuit(circuits, output_name, callback)
  File "/lib/python3.9/site-packages/qiskit/transpiler/passmanager.py", line 276, in _run_single_circuit
    result = running_passmanager.run(circuit, output_name=output_name, callback=callback)
  File "/lib/python3.9/site-packages/qiskit/transpiler/runningpassmanager.py", line 122, in run
    dag = self._do_pass(pass_, dag, passset.options)
  File "/lib/python3.9/site-packages/qiskit/transpiler/runningpassmanager.py", line 153, in _do_pass
    dag = self._run_this_pass(pass_, dag)
  File "/lib/python3.9/site-packages/qiskit/transpiler/runningpassmanager.py", line 165, in _run_this_pass
    new_dag = pass_.run(dag)
  File "/lib/python3.9/site-packages/qiskit/transpiler/passes/basis/unroll_custom_definitions.py", line 87, in run
    raise QiskitError("Cannot unroll the circuit to the given basis, %s. "
qiskit.exceptions.QiskitError: "Cannot unroll the circuit to the given basis, ['id', 'rz', 'sx', 'x', 'cx']. Instruction snapshot not found in equivalence library and no rule found to expand."


----------------------------------------------------------------------
Ran 1 test in 0.003s

FAILED (errors=1)
```

### Steps to reproduce the problem

Run `python -m unittest test.terra.backends.test_qasm_simulator.TestQasmSimulator.test_gate_density_matrix_075`, for example.

### What is the expected behavior?

Pass the test.

**Comment by vvilpas** [comment]
Everything is working again.
