### ISSUE TITLE
Aer's simulators and Terra's statevector class give different probabilities on partial qubits

### ISSUE THREAD

**Issue by ShellyGarion** [Qiskit/qiskit-aer#1235]
### Informations

- **Qiskit Aer version**:  0.8.1 (qiskit-0.25.1)
- **Python version**:
- **Operating system**:

### What is the current behavior?
When I run Aer simulator of a 4-qubit circuit and measure only one qubit, 
the `statevector` class in Terra gives a `probabilities` vector of length 2 while Aer's simulators give a `probabilities` vector of length 16.
Which one is correct?

### Steps to reproduce the problem
```
        from qiskit import transpile, assemble
        from qiskit.providers.aer import AerSimulator
        from qiskit.quantum_info import Statevector
        from qiskit.quantum_info.random import random_clifford
 
        num_qubits = 4
        cliff = random_clifford(num_qubits, seed=1234)
        qargs = [1]
        qc = cliff.to_circuit()
        target = Statevector(qc).probabilities(qargs)
        target_dict = Statevector(qc).probabilities_dict(qargs, decimals=2)

        print(cliff, num_qubits, qargs)
        print ("qi statevector", target_dict, target)

        for method in ['stabilizer', 'statevector']:
             SIMULATOR = AerSimulator(method=method)
             label = 'probs'
             circ = transpile(qc, SIMULATOR)
             circ.save_probabilities(qargs, label=label)
             qobj = assemble(circ)
             result = SIMULATOR.run(qobj).result()
             output = result.data(0)[label]
             print("Aer", method, output)
```

The output is: 

```
Stabilizer = ['-ZZZZ', '-ZYIY', '+IIZI', '+YIZX'], Destabilizer = ['-XIZZ', '+YZIX', '-ZYYI', '+XXII'] 4 [1] 
qi statevector {'0': 1.0} [1.0000000e+00 7.9243455e-35]
Aer stabilizer [0.   0.25 0.   0.   0.25 0.   0.   0.   0.25 0.   0.   0.   0.   0.25 0.   0.  ]
Aer statevector [3.81548692e-33 2.50000000e-01 2.57380500e-35 3.30437338e-35
 2.50000000e-01 1.10470018e-34 6.60874676e-35 9.86361644e-33
 2.50000000e-01 4.71803384e-33 6.60874676e-35 1.66261699e-32
 9.68634381e-34 2.50000000e-01 3.87451647e-33 6.60874676e-35]

```

In addition, when I run this test locally: 
https://github.com/Qiskit/qiskit-aer/blob/master/test/terra/backends/qasm_simulator/qasm_save_probabilities.py
I get the following errors (due to different outputs dimensions):
```
======================================================================
ERROR: test_save_probabilities_1__0__1_ (__main__.QasmSaveProbabilitiesTests)
Test save probabilities instruction
----------------------------------------------------------------------
testtools.testresult.real._StringException: Traceback (most recent call last):
  File "/opt/anaconda3/envs/ShellyTerra/lib/python3.7/site-packages/ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "/home/shelly/Quantum/qiskit-terra/test/python/quantum_info/states/tmp.py", line 54, in test_save_probabilities
    self.assertTrue(np.allclose(value, target))
  File "<__array_function__ internals>", line 6, in allclose
  File "/opt/anaconda3/envs/ShellyTerra/lib/python3.7/site-packages/numpy/core/numeric.py", line 2159, in allclose
    res = all(isclose(a, b, rtol=rtol, atol=atol, equal_nan=equal_nan))
  File "<__array_function__ internals>", line 6, in isclose
  File "/opt/anaconda3/envs/ShellyTerra/lib/python3.7/site-packages/numpy/core/numeric.py", line 2260, in isclose
    return within_tol(x, y, atol, rtol)
  File "/opt/anaconda3/envs/ShellyTerra/lib/python3.7/site-packages/numpy/core/numeric.py", line 2246, in within_tol
    return less_equal(abs(x-y), atol + rtol * abs(y))
ValueError: operands could not be broadcast together with shapes (8,) (4,)


```
### What is the expected behavior?

Terra's `statevector` class and Aer's simulators should give the same probability vectors (of the same dimension).
Aer's test should have detected these errors.

**Comment by ShellyGarion** [comment]
closing since uninstalling qiskit-aer and installing it again seem to make it work :)
