### ISSUE TITLE
PulseSimulator fails on a simple example

### ISSUE THREAD

**Issue by rsln-s** [Qiskit/qiskit-aer#1246]
### Informations

- **Qiskit Aer version**: 0.8.2
- **Python version**: 3.8.8
- **Operating system**: macOS 11.2.3

### What is the current behavior?

PulseSimulator fails (throws an exception) on a simple schedule constructed from bell state preparation circuit.

### Steps to reproduce the problem

```python
import qiskit
from qiskit.tools.jupyter import *
from qiskit import IBMQ, QuantumCircuit, execute, transpile, schedule                                                                                                                                                                                         
 
IBMQ.load_account()
provider = IBMQ.get_provider('REDACTED')
backend = provider.get_backend('ibmq_casablanca')
 
qc = QuantumCircuit(2)
qc.h(1)
qc.cx(0,1)
qc.measure_all()
 
sched = schedule(transpile(qc, backend), backend)
 
# from https://qiskit.org/documentation/stubs/qiskit.providers.aer.PulseSimulator.html#qiskit.providers.aer.PulseSimulator
res = execute(sched, backend=qiskit.providers.aer.PulseSimulator.from_backend(backend)).result()
```

Traceback:
```
/Users/ruslan/soft/anaconda3/envs/qiskit_latest/lib/python3.8/site-packages/qiskit/providers/aer/pulse/system_models/string_model_parser/string_model_parser.py:280: DeprecationWarning: Using the `__mul__` operator `A * B` as shorthand for `A.dot(B)` is deprecated as of version 0.17.0 and will be  removed no earlier than 3 months after the release date. As an alternative, use the compose operator `B & A` in place of `A * B` as a replacement.
  stack.append(op1 * op2)
/Users/ruslan/soft/anaconda3/envs/qiskit_latest/lib/python3.8/site-packages/qiskit/compiler/assembler.py:309: RuntimeWarning: Dynamic rep rates are supported on this backend. 'rep_delay' will be used instead of 'rep_time'.
  warnings.warn("Dynamic rep rates are supported on this backend. 'rep_delay' will be "
Traceback (most recent call last):
  File "test.py", line 17, in <module>
    res = execute(sched, backend=qiskit.providers.aer.PulseSimulator.from_backend(backend)).result()
  File "/Users/ruslan/soft/anaconda3/envs/qiskit_latest/lib/python3.8/site-packages/qiskit/providers/aer/aerjob.py", line 43, in _wrapper
    return func(self, *args, **kwargs)
  File "/Users/ruslan/soft/anaconda3/envs/qiskit_latest/lib/python3.8/site-packages/qiskit/providers/aer/aerjob.py", line 102, in result
    return self._future.result(timeout=timeout)
  File "/Users/ruslan/soft/anaconda3/envs/qiskit_latest/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/Users/ruslan/soft/anaconda3/envs/qiskit_latest/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/Users/ruslan/soft/anaconda3/envs/qiskit_latest/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/ruslan/soft/anaconda3/envs/qiskit_latest/lib/python3.8/site-packages/qiskit/providers/aer/backends/aerbackend.py", line 265, in _run
    output = self._execute(qobj)
  File "/Users/ruslan/soft/anaconda3/envs/qiskit_latest/lib/python3.8/site-packages/qiskit/providers/aer/backends/pulse_simulator.py", line 276, in _execute
    return pulse_controller(qobj)
  File "/Users/ruslan/soft/anaconda3/envs/qiskit_latest/lib/python3.8/site-packages/qiskit/providers/aer/pulse/controllers/pulse_controller.py", line 110, in pulse_controller
    digested_qobj = digest_pulse_qobj(qobj,
  File "/Users/ruslan/soft/anaconda3/envs/qiskit_latest/lib/python3.8/site-packages/qiskit/providers/aer/pulse/controllers/digest_pulse_qobj.py", line 120, in digest_pulse_qobj
    exp_struct = experiment_to_structs(exp,
  File "/Users/ruslan/soft/anaconda3/envs/qiskit_latest/lib/python3.8/site-packages/qiskit/providers/aer/pulse/controllers/digest_pulse_qobj.py", line 358, in experiment_to_structs
    pulse_int = pulse_to_int[inst['name']]
KeyError: 'parametric_pulse'
```

### What is the expected behavior?

PulseSimulator should not throw an exception.

### Suggested solutions

N/A

**Comment by DanPuzzuoli** [comment]
A solution to the main comment in this issue is to set override the configuration parameter `parametric_pulses` to be `[]` when constructing the pulse simulator instance from backend.

However, this issue also arises in a similar use case, which would not be fixed by the above solution:

```
from qiskit import *
from qiskit.pulse import *
from qiskit.test.mock import FakeValencia
import numpy as np
backend = FakeValencia()
defaults = backend.defaults()
config = backend.configuration()
inst_sched_map = defaults.instruction_schedule_map
measure = inst_sched_map.get('measure', qubits=config.meas_map[0])
prog = Schedule()
d0 = DriveChannel(0)
d1 = DriveChannel(1)
prog += Play(Gaussian(100, 0.5, 20),d1)
prog += Play(Waveform([np.exp(1j*i*0.05) for i in range(160)]), d0)
prog += measure << prog.duration
prog_run = assemble(prog,backend=backend,meas_level=2)
job = backend.run(prog_run)
results = job.result()
results.get_counts()
```

In this case, the `qobj` is being assembled using a fake backend, and then the pulse simulator is being invoked by the fake backend when `run` is called. However, in this flow, the `qobj` is assembled using the configuration of the fake backend, which the pulse simulator has no control over, and therefore cannot override the assembly behaviour. 

Should the user just be passing the schedules directly, and the pulse simulator can assemble the `qobj` however it wants?

**Comment by rsln-s** [comment]
@DanPuzzuoli may I ask you to share an example of how to override the configuration parameter `parametric_pulses` to be `[]` when constructing the pulse simulator instance from backend?

**Comment by DanPuzzuoli** [comment]
Yes for sure, in the meantime, you can do this:
```
backend = provider.get_backend('ibmq_casablanca')
sim_backend = PulseSimulator.from_backend(backend)
sim_backend.configuration().parametric_pulses = []
```
then use the `sim_backend` when assembling, instead of `backend`.

Basically, `PulseSimulator.from_backend` copies over configuration data, but overrides certain parameters based on what the simulator needs: essentially, things like `sim_backend.configuration().parametric_pulses = []`. So you can do this manually until we've determined a permanent solution.

**Comment by DanPuzzuoli** [comment]
In the end the plan to address this issue is simple:

- Set `config.parametric_pulses = []` in `PulseSimulator.from_backend`
- Raise error with helpful message if a parametric pulse is encountered when interpreting pulse schedules
