### ISSUE TITLE
Unitary simulation segmentation fault with 16 qubits

### ISSUE THREAD

**Issue by mhinkie** [Qiskit/qiskit-aer#1260]
### Informations

- **Qiskit Aer version**: 0.8.2
- **Python version**: 3.8.5
- **Operating system**: KDE neon 5.21

### What is the current behavior?
aer_simulator with save_unitary() instruction gives a segmentation fault when using 16 qubits, while working as expected with 15 qubits. It does not indicate if this is a problem with resource availability (not enough RAM to simulate), or some other problem.

### Steps to reproduce the problem
```
from qiskit import QuantumCircuit, Aer, transpile

circ = QuantumCircuit(15)

simulator = Aer.get_backend('aer_simulator')
circ = transpile(circ, simulator)
circ.save_unitary()
result = simulator.run(circ).result()
unitary = result.get_unitary(circ)

print(unitary)
```

gives: 
```
$ python3 test.py 
[[1.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 1.+0.j 0.+0.j ... 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 1.+0.j ... 0.+0.j 0.+0.j 0.+0.j]
 ...
 [0.+0.j 0.+0.j 0.+0.j ... 1.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 1.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 1.+0.j]]
```

But:
```
from qiskit import QuantumCircuit, Aer, transpile

circ = QuantumCircuit(16)

simulator = Aer.get_backend('aer_simulator')
circ = transpile(circ, simulator)
circ.save_unitary()
result = simulator.run(circ).result()
unitary = result.get_unitary(circ)

print(unitary)
```

gives:
```
$ python3 test.py 
Segmentation fault
```

### What is the expected behavior?
If the segmentation fault comes from an error in the simulator, the expected result should be the identity matrix (for this particular circuit) for 16 qubits.
If the segmentation fault stems from missing memory, the expected result would be an error message similar to:
```
from qiskit import QuantumCircuit, QuantumRegister, Aer, transpile

reg = QuantumRegister(36)
circ = QuantumCircuit(reg)

circ.h(reg)
circ.x(reg)
circ.measure_all()

simulator = Aer.get_backend('aer_simulator')
circ = transpile(circ, simulator)
result = simulator.run(circ).result()
counts = result.get_counts(circ)

print(counts)
```

Output:
```
$ python3 test2.py 
Simulation failed and returned the following error message:
ERROR:  [Experiment 0] Insufficient memory to run circuit "circuit-0" using the statevector simulator.
Traceback (most recent call last):
  File "test2.py", line 14, in <module>
    counts = result.get_counts(circ)
  File "/home/alex/anaconda3/lib/python3.8/site-packages/qiskit/result/result.py", line 263, in get_counts
    exp = self._get_experiment(key)
  File "/home/alex/anaconda3/lib/python3.8/site-packages/qiskit/result/result.py", line 370, in _get_experiment
    raise QiskitError('Data for experiment "%s" could not be found.' %
qiskit.exceptions.QiskitError: 'Data for experiment "circuit-0" could not be found.'
```

**Comment by hhorii** [comment]
@mhinkie Thank you for your reporting this bug and I'm very sorry that my response is lazy. I'm now trying to reproduce your situation. I guess that we need check codes to verify that memory allocation is succeeded around [here](https://github.com/Qiskit/qiskit-aer/blob/main/src/simulators/statevector/qubitvector.hpp#L796-L800).

**Comment by rsln-s** [comment]
@hhorii same issue may be happening in #1288, #1289.
