### ISSUE TITLE
Failed building qiskit-aer from source

### ISSUE THREAD

**Issue by tj-amano** [Qiskit/qiskit-aer#1664]
### Informations

- **Qiskit version**: install from source at https://github.com/Qiskit/qiskit-aer
- **Python version**: 3.9.5
- **Python virtual environment**: venv
- **Operating system**: macOS12.6, M1 Max

### What is the current behavior?
During the installation of "requirements-dev.txt", I encountered the following error.

```
Collecting stestr>=2.5.0
  Using cached stestr-4.0.1-py3-none-any.whl (117 kB)
Collecting cmake!=3.17.0,!=3.17.1
  Using cached cmake-3.25.0-py2.py3-none-macosx_10_10_universal2.macosx_10_10_x86_64.macosx_11_0_arm64.macosx_11_0_universal2.whl (45.1 MB)
Collecting conan>=1.40.0
  Using cached conan-1.54.0-py3-none-any.whl
Collecting scikit-build>=0.11.0
  Using cached scikit_build-0.16.2-py3-none-any.whl (78 kB)
Collecting asv
  Using cached asv-0.5.1.tar.gz (487 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting cvxpy<1.1.15,>=1.0.0
  Using cached cvxpy-1.1.14-cp39-cp39-macosx_12_0_arm64.whl
Collecting pylint
  Using cached pylint-2.15.6-py3-none-any.whl (508 kB)
Collecting pycodestyle
  Using cached pycodestyle-2.9.1-py2.py3-none-any.whl (41 kB)
Collecting Sphinx>=1.8.3
  Using cached sphinx-5.3.0-py3-none-any.whl (3.2 MB)
Collecting sphinx-rtd-theme>=0.4.0
  Using cached sphinx_rtd_theme-1.1.1-py2.py3-none-any.whl (2.8 MB)
Collecting sphinx-tabs>=1.1.11
  Using cached sphinx_tabs-3.4.1-py3-none-any.whl (10.0 kB)
Collecting sphinx-automodapi
  Using cached sphinx_automodapi-0.14.1-py3-none-any.whl (77 kB)
Collecting jupyter-sphinx
  Using cached jupyter_sphinx-0.4.0-py3-none-any.whl (21 kB)
Collecting reno>=3.4.0
  Using cached reno-3.5.0-py3-none-any.whl (70 kB)
Collecting ddt!=1.4.0,>=1.2.0
  Using cached ddt-1.6.0-py2.py3-none-any.whl (7.1 kB)
Collecting cliff>=2.8.0
  Using cached cliff-4.1.0-py3-none-any.whl (81 kB)
Collecting python-subunit>=1.4.0
  Using cached python_subunit-1.4.2-py3-none-any.whl (106 kB)
Collecting testtools>=2.2.0
  Using cached testtools-2.5.0-py3-none-any.whl (181 kB)
Collecting PyYAML>=3.10.0
  Using cached PyYAML-6.0-cp39-cp39-macosx_11_0_arm64.whl (173 kB)
Collecting pbr!=2.1.0,!=4.0.0,!=4.0.1,!=4.0.2,!=4.0.3,>=2.0.0
  Using cached pbr-5.11.0-py2.py3-none-any.whl (112 kB)
Collecting voluptuous>=0.8.9
  Using cached voluptuous-0.13.1-py3-none-any.whl (29 kB)
Collecting future
  Using cached future-0.18.2-py3-none-any.whl
Collecting fixtures>=3.0.0
  Using cached fixtures-4.0.1-py3-none-any.whl
Collecting PyJWT<3.0.0,>=2.4.0
  Using cached PyJWT-2.6.0-py3-none-any.whl (20 kB)
Collecting colorama<0.5.0,>=0.3.3
  Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting bottle<0.13,>=0.12.8
  Using cached bottle-0.12.23-py3-none-any.whl (90 kB)
Collecting node-semver==0.6.1
  Using cached node_semver-0.6.1-py3-none-any.whl (10 kB)
Collecting urllib3<1.27,>=1.26.6
  Using cached urllib3-1.26.12-py2.py3-none-any.whl (140 kB)
Collecting patch-ng<1.18,>=1.17.4
  Using cached patch_ng-1.17.4-py3-none-any.whl
Collecting Jinja2<4.0.0,>=3.0
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting requests<3.0.0,>=2.25
  Using cached requests-2.28.1-py3-none-any.whl (62 kB)
Collecting six<=1.16.0,>=1.10.0
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting pluginbase>=0.5
  Using cached pluginbase-1.0.1-py3-none-any.whl
Collecting python-dateutil<3,>=2.7.0
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting fasteners>=0.14.1
  Using cached fasteners-0.18-py3-none-any.whl (18 kB)
Collecting tqdm<5,>=4.28.1
  Using cached tqdm-4.64.1-py2.py3-none-any.whl (78 kB)
Collecting pygments<3.0,>=2.0
  Using cached Pygments-2.13.0-py3-none-any.whl (1.1 MB)
Collecting packaging
  Using cached packaging-21.3-py3-none-any.whl (40 kB)
Collecting distro
  Using cached distro-1.8.0-py3-none-any.whl (20 kB)
Requirement already satisfied: setuptools>=42.0.0 in /Users/tj/.venv/qiskit-aer-dev/lib/python3.9/site-packages (from scikit-build>=0.11.0->-r requirements-dev.txt (line 4)) (56.0.0)
Collecting wheel>=0.32.0
  Using cached wheel-0.38.4-py3-none-any.whl (36 kB)
Collecting osqp>=0.4.1
  Using cached osqp-0.6.2.post5.tar.gz (226 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'error'
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [85 lines of output]
      Collecting oldest-supported-numpy
        Using cached oldest_supported_numpy-2022.11.19-py3-none-any.whl (4.9 kB)
      Collecting setuptools>=40.8.0
        Using cached setuptools-65.6.0-py3-none-any.whl (1.2 MB)
      Collecting wheel
        Using cached wheel-0.38.4-py3-none-any.whl (36 kB)
      Collecting setuptools_scm>=6.2
        Using cached setuptools_scm-7.0.5-py3-none-any.whl (42 kB)
      Collecting qdldl
        Using cached qdldl-0.1.5.post2.tar.gz (69 kB)
        Preparing metadata (setup.py): started
        Preparing metadata (setup.py): finished with status 'done'
      Collecting numpy==1.21.0
        Using cached numpy-1.21.0-cp39-cp39-macosx_11_0_arm64.whl (12.1 MB)
      Collecting packaging>=20.0
        Using cached packaging-21.3-py3-none-any.whl (40 kB)
      Collecting typing-extensions
        Using cached typing_extensions-4.4.0-py3-none-any.whl (26 kB)
      Collecting tomli>=1.0.0
        Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
      Collecting scipy>=0.13.2
        Using cached scipy-1.9.3-cp39-cp39-macosx_12_0_arm64.whl (28.6 MB)
      Collecting pyparsing!=3.0.5,>=2.0.2
        Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
      Installing collected packages: wheel, typing-extensions, tomli, setuptools, pyparsing, numpy, scipy, packaging, oldest-supported-numpy, setuptools_scm, qdldl
        DEPRECATION: qdldl is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
        Running setup.py install for qdldl: started
        Running setup.py install for qdldl: finished with status 'error'
        error: subprocess-exited-with-error
      
        × Running setup.py install for qdldl did not run successfully.
        │ exit code: 1
        ╰─> [42 lines of output]
            running install
            running build
            running build_ext
            -- The C compiler identification is unknown
            -- The CXX compiler identification is unknown
            -- Detecting C compiler ABI info
            -- Detecting C compiler ABI info - failed
            -- Check for working C compiler: /usr/bin/cc
            -- Check for working C compiler: /usr/bin/cc - broken
            CMake Error at /opt/homebrew/Cellar/cmake/3.24.2/share/cmake/Modules/CMakeTestCCompiler.cmake:69 (message):
              The C compiler
      
                "/usr/bin/cc"
      
              is not able to compile a simple test program.
      
              It fails with the following output:
      
                Change Dir: /private/var/folders/12/r2kqphbx64l3m7464rpq2lhh0000gn/T/pip-install-b07gs6p3/qdldl_28531b18dac4483798aa4a3610f4ceab/c/build/CMakeFiles/CMakeTmp
      
                Run Build Command(s):/usr/bin/make -f Makefile cmTC_ebd9d/fast && xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
      
      
      
      
      
              CMake will not be able to correctly generate this project.
            Call Stack (most recent call first):
              CMakeLists.txt:4 (project)
      
      
            -- Configuring incomplete, errors occurred!
            See also "/private/var/folders/12/r2kqphbx64l3m7464rpq2lhh0000gn/T/pip-install-b07gs6p3/qdldl_28531b18dac4483798aa4a3610f4ceab/c/build/CMakeFiles/CMakeOutput.log".
            See also "/private/var/folders/12/r2kqphbx64l3m7464rpq2lhh0000gn/T/pip-install-b07gs6p3/qdldl_28531b18dac4483798aa4a3610f4ceab/c/build/CMakeFiles/CMakeError.log".
            xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
            building 'qdldl' extension
            creating build
            creating build/temp.macosx-12.6-arm64-3.9
            creating build/temp.macosx-12.6-arm64-3.9/cpp
            clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/opt/homebrew/opt/openblas/include -Ic -Ic/qdldl/include -I/Users/tj/.venv/qiskit-aer-dev/lib/python3.9/site-packages/pybind11/include -I/Users/tj/.venv/qiskit-aer-dev/lib/python3.9/site-packages/pybind11/include -I/Users/tj/.venv/qiskit-aer-dev/include -I/Users/tj/.pyenv/versions/3.9.5/include/python3.9 -c cpp/qdldl.cpp -o build/temp.macosx-12.6-arm64-3.9/cpp/qdldl.o -O3 -std=c++11
            xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
            error: command '/usr/bin/clang' failed with exit code 1
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: legacy-install-failure
      
      × Encountered error while trying to install package.
      ╰─> qdldl
      
      note: This is an issue with the package mentioned above, not pip.
      hint: See above for output from the failure.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

### Steps to reproduce the problem
- clone qiskit-aer from `https://github.com/Qiskit/qiskit-aer`
- make python virtual environment for qiskit-dev `python -m venv ~/.venv/qiskit-dev`
- upgrading pip, and `pip install -r requirements-dev.txt` refer to [CONTRIBUTING.md](https://github.com/Qiskit/qiskit-aer/blob/main/CONTRIBUTING.md#install-from-source)`

### What is the expected behavior?
Complete the installation without any errors.

### Suggested solutions
Checking the installation logs, it appears that the `numpy` installation did not go well during the `cvxpy` installation.

We suspect that this is because the version of numpy that cvxpy is trying to install is a version from before Apple released the m1 chip, so the build is not going well.

**Comment by jakelishman** [comment]
It looks like it's trying to build `qdldl` from source (a requirement of cvxpy), but you don't seem to have a working C compiler.  Have you installed the macOS command-line tools (`xcode-select --install`?  You'll need a working C/C++ to build Aer even once the dependencies have been built.

**Comment by tj-amano** [comment]
Oh, sorry.
I misunderstood that it was installed, but it wasn't.
Fortunately, the installation of "requirements-dev.txt" was completed with `xcode-select --install`.

```
Processing /Users/tj/project/qiskit-aer
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: numpy>=1.16.3 in /Users/tj/.venv/qiskit-aer-dev/lib/python3.9/site-packages (from qiskit-aer==0.11.1) (1.23.5)
Requirement already satisfied: scipy>=1.0 in /Users/tj/.venv/qiskit-aer-dev/lib/python3.9/site-packages (from qiskit-aer==0.11.1) (1.9.3)
Collecting qiskit-terra>=0.21.0
  Using cached qiskit_terra-0.22.2-cp39-cp39-macosx_11_0_arm64.whl (4.4 MB)
Requirement already satisfied: psutil>=5 in /Users/tj/.venv/qiskit-aer-dev/lib/python3.9/site-packages (from qiskit-terra>=0.21.0->qiskit-aer==0.11.1) (5.9.4)
Collecting ply>=3.10
  Using cached ply-3.11-py2.py3-none-any.whl (49 kB)
Requirement already satisfied: stevedore>=3.0.0 in /Users/tj/.venv/qiskit-aer-dev/lib/python3.9/site-packages (from qiskit-terra>=0.21.0->qiskit-aer==0.11.1) (4.1.1)
Requirement already satisfied: dill>=0.3 in /Users/tj/.venv/qiskit-aer-dev/lib/python3.9/site-packages (from qiskit-terra>=0.21.0->qiskit-aer==0.11.1) (0.3.6)
Collecting symengine>=0.9
  Using cached symengine-0.9.2-cp39-cp39-macosx_11_0_arm64.whl (14.9 MB)
Collecting sympy>=1.3
  Using cached sympy-1.11.1-py3-none-any.whl (6.5 MB)
Collecting retworkx>=0.11.0
  Using cached retworkx-0.12.0-py3-none-any.whl (10 kB)
Requirement already satisfied: python-dateutil>=2.8.0 in /Users/tj/.venv/qiskit-aer-dev/lib/python3.9/site-packages (from qiskit-terra>=0.21.0->qiskit-aer==0.11.1) (2.8.2)
Requirement already satisfied: six>=1.5 in /Users/tj/.venv/qiskit-aer-dev/lib/python3.9/site-packages (from python-dateutil>=2.8.0->qiskit-terra>=0.21.0->qiskit-aer==0.11.1) (1.16.0)
Collecting rustworkx==0.12.0
  Using cached rustworkx-0.12.0-cp39-cp39-macosx_11_0_arm64.whl (1.4 MB)
Requirement already satisfied: pbr!=2.1.0,>=2.0.0 in /Users/tj/.venv/qiskit-aer-dev/lib/python3.9/site-packages (from stevedore>=3.0.0->qiskit-terra>=0.21.0->qiskit-aer==0.11.1) (5.11.0)
Collecting mpmath>=0.19
  Using cached mpmath-1.2.1-py3-none-any.whl (532 kB)
Building wheels for collected packages: qiskit-aer
  Building wheel for qiskit-aer (pyproject.toml): started
  Building wheel for qiskit-aer (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error
  
  × Building wheel for qiskit-aer (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [106 lines of output]
      
      
      --------------------------------------------------------------------------------
      -- Trying "Ninja" generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      -- The C compiler identification is AppleClang 14.0.0.14000029
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- The CXX compiler identification is AppleClang 14.0.0.14000029
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Configuring done
      -- Generating done
      -- Build files have been written to: /Users/tj/project/qiskit-aer/_cmake_test_compile/build
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying "Ninja" generator - success
      --------------------------------------------------------------------------------
      
      Configuring Project
        Working directory:
          /Users/tj/project/qiskit-aer/_skbuild/macosx-13.0-arm64-3.9/cmake-build
        Command:
          /private/var/folders/12/r2kqphbx64l3m7464rpq2lhh0000gn/T/pip-build-env-a_iz9md3/overlay/lib/python3.9/site-packages/cmake/data/bin/cmake /Users/tj/project/qiskit-aer -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/Users/tj/project/qiskit-aer/_skbuild/macosx-13.0-arm64-3.9/cmake-install -DPYTHON_VERSION_STRING:STRING=3.9.5 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/private/var/folders/12/r2kqphbx64l3m7464rpq2lhh0000gn/T/pip-build-env-a_iz9md3/overlay/lib/python3.9/site-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/Users/tj/.venv/qiskit-aer-dev/bin/python -DPYTHON_INCLUDE_DIR:PATH=/Users/tj/.pyenv/versions/3.9.5/include/python3.9 -DPYTHON_LIBRARY:PATH=/Users/tj/.pyenv/versions/3.9.5/lib/libpython3.9.a -DPython_EXECUTABLE:PATH=/Users/tj/.venv/qiskit-aer-dev/bin/python -DPython_ROOT_DIR:PATH=/Users/tj/.venv/qiskit-aer-dev -DPython_INCLUDE_DIR:PATH=/Users/tj/.pyenv/versions/3.9.5/include/python3.9 -DPython_FIND_REGISTRY:STRING=NEVER -DPython_NumPy_INCLUDE_DIRS:PATH=/private/var/folders/12/r2kqphbx64l3m7464rpq2lhh0000gn/T/pip-build-env-a_iz9md3/overlay/lib/python3.9/site-packages/numpy/core/include -DPython3_EXECUTABLE:PATH=/Users/tj/.venv/qiskit-aer-dev/bin/python -DPython3_ROOT_DIR:PATH=/Users/tj/.venv/qiskit-aer-dev -DPython3_INCLUDE_DIR:PATH=/Users/tj/.pyenv/versions/3.9.5/include/python3.9 -DPython3_FIND_REGISTRY:STRING=NEVER -DPython3_NumPy_INCLUDE_DIRS:PATH=/private/var/folders/12/r2kqphbx64l3m7464rpq2lhh0000gn/T/pip-build-env-a_iz9md3/overlay/lib/python3.9/site-packages/numpy/core/include -DCMAKE_MAKE_PROGRAM:FILEPATH=/private/var/folders/12/r2kqphbx64l3m7464rpq2lhh0000gn/T/pip-build-env-a_iz9md3/overlay/lib/python3.9/site-packages/ninja/data/bin/ninja -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_OSX_DEPLOYMENT_TARGET:STRING=13.0 -DCMAKE_OSX_ARCHITECTURES:STRING=arm64
      
      -- Performing Test flag_supported
      -- Performing Test flag_supported - Success
      -- Performing Test flag_supported
      -- Performing Test flag_supported - Success
      -- Performing Test flag_supported
      -- Performing Test flag_supported - Success
      -- Performing Test flag_supported
      -- Performing Test flag_supported - Success
      -- Performing Test flag_supported
      -- Performing Test flag_supported - Success
      -- Performing Test flag_supported
      -- Performing Test flag_supported - Success
      -- Performing Test flag_supported
      -- Performing Test flag_supported - Success
      -- Performing Test flag_supported
      -- Performing Test flag_supported - Success
      -- Performing Test flag_supported
      -- Performing Test flag_supported - Success
      -- Performing Test flag_supported
      -- Performing Test flag_supported - Success
      -- Performing Test flag_supported
      -- Performing Test flag_supported - Success
      -- Conan: Automatic detection of conan settings from cmake
      In file included from <stdin>:1:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/string:519:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/__debug:14:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/iosfwd:98:
      In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/__mbstate_t.h:29:
      /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/wchar.h:123:15: fatal error: 'wchar.h' file not found
      #include_next <wchar.h>
                    ^~~~~~~~~
      1 error generated.
      -- Conan: Settings= -s;arch=armv8;-s;build_type=Release;-s;compiler=apple-clang;-s;compiler.version=14.0;-s;compiler.libcxx=libc++;-s;arch_build=armv8
      -- Conan: checking conan executable
      -- Conan: Found program /private/var/folders/12/r2kqphbx64l3m7464rpq2lhh0000gn/T/pip-build-env-2k102k4e/overlay/bin/conan
      -- Conan: Version found
      -- Conan executing: /private/var/folders/12/r2kqphbx64l3m7464rpq2lhh0000gn/T/pip-build-env-2k102k4e/overlay/bin/conan install . -s arch=armv8 -s build_type=Release -s compiler=apple-clang -s compiler.version=14.0 -s compiler.libcxx=libc++ -s arch_build=armv8 -e=CONAN_CMAKE_PROGRAM=/private/var/folders/12/r2kqphbx64l3m7464rpq2lhh0000gn/T/pip-build-env-a_iz9md3/overlay/lib/python3.9/site-packages/cmake/data/bin/cmake -g=cmake --build=missing
      CMake Error at cmake/conan.cmake:402 (message):
        Conan install failed='No such file or directory'
      Call Stack (most recent call first):
        cmake/conan.cmake:497 (conan_cmake_install)
        cmake/conan_utils.cmake:61 (conan_cmake_run)
        cmake/dependency_utils.cmake:20 (setup_conan)
        CMakeLists.txt:144 (setup_dependencies)
      
      
      -- Configuring incomplete, errors occurred!
      See also "/Users/tj/project/qiskit-aer/_skbuild/macosx-13.0-arm64-3.9/cmake-build/CMakeFiles/CMakeOutput.log".
      See also "/Users/tj/project/qiskit-aer/_skbuild/macosx-13.0-arm64-3.9/cmake-build/CMakeFiles/CMakeError.log".
      Traceback (most recent call last):
        File "/private/var/folders/12/r2kqphbx64l3m7464rpq2lhh0000gn/T/pip-build-env-a_iz9md3/overlay/lib/python3.9/site-packages/skbuild/setuptools_wrap.py", line 632, in setup
          env = cmkr.configure(
        File "/private/var/folders/12/r2kqphbx64l3m7464rpq2lhh0000gn/T/pip-build-env-a_iz9md3/overlay/lib/python3.9/site-packages/skbuild/cmaker.py", line 334, in configure
          raise SKBuildError(
      
      An error occurred while configuring with CMake.
        Command:
          /private/var/folders/12/r2kqphbx64l3m7464rpq2lhh0000gn/T/pip-build-env-a_iz9md3/overlay/lib/python3.9/site-packages/cmake/data/bin/cmake /Users/tj/project/qiskit-aer -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/Users/tj/project/qiskit-aer/_skbuild/macosx-13.0-arm64-3.9/cmake-install -DPYTHON_VERSION_STRING:STRING=3.9.5 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/private/var/folders/12/r2kqphbx64l3m7464rpq2lhh0000gn/T/pip-build-env-a_iz9md3/overlay/lib/python3.9/site-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/Users/tj/.venv/qiskit-aer-dev/bin/python -DPYTHON_INCLUDE_DIR:PATH=/Users/tj/.pyenv/versions/3.9.5/include/python3.9 -DPYTHON_LIBRARY:PATH=/Users/tj/.pyenv/versions/3.9.5/lib/libpython3.9.a -DPython_EXECUTABLE:PATH=/Users/tj/.venv/qiskit-aer-dev/bin/python -DPython_ROOT_DIR:PATH=/Users/tj/.venv/qiskit-aer-dev -DPython_INCLUDE_DIR:PATH=/Users/tj/.pyenv/versions/3.9.5/include/python3.9 -DPython_FIND_REGISTRY:STRING=NEVER -DPython_NumPy_INCLUDE_DIRS:PATH=/private/var/folders/12/r2kqphbx64l3m7464rpq2lhh0000gn/T/pip-build-env-a_iz9md3/overlay/lib/python3.9/site-packages/numpy/core/include -DPython3_EXECUTABLE:PATH=/Users/tj/.venv/qiskit-aer-dev/bin/python -DPython3_ROOT_DIR:PATH=/Users/tj/.venv/qiskit-aer-dev -DPython3_INCLUDE_DIR:PATH=/Users/tj/.pyenv/versions/3.9.5/include/python3.9 -DPython3_FIND_REGISTRY:STRING=NEVER -DPython3_NumPy_INCLUDE_DIRS:PATH=/private/var/folders/12/r2kqphbx64l3m7464rpq2lhh0000gn/T/pip-build-env-a_iz9md3/overlay/lib/python3.9/site-packages/numpy/core/include -DCMAKE_MAKE_PROGRAM:FILEPATH=/private/var/folders/12/r2kqphbx64l3m7464rpq2lhh0000gn/T/pip-build-env-a_iz9md3/overlay/lib/python3.9/site-packages/ninja/data/bin/ninja -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_OSX_DEPLOYMENT_TARGET:STRING=13.0 -DCMAKE_OSX_ARCHITECTURES:STRING=arm64
        Source directory:
          /Users/tj/project/qiskit-aer
        Working directory:
          /Users/tj/project/qiskit-aer/_skbuild/macosx-13.0-arm64-3.9/cmake-build
      Please see CMake's output for more information.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for qiskit-aer
Failed to build qiskit-aer
ERROR: Could not build wheels for qiskit-aer, which is required to install pyproject.toml-based projects
```

**Comment by Hamaad1** [comment]
It is easy to solve, Create a virtual environment with Python version 3.12. Then install with the command "pip install qiskit_aer". 

![Image](https://github.com/user-attachments/assets/09452135-9e03-4460-80a0-194dbf873ff2)
