### ISSUE TITLE
`AerSampler` fails with a circuit and split registers

### ISSUE THREAD

**Issue by t-imamichi** [Qiskit/qiskit-aer#1679]
### Informations

- **Qiskit Aer version**: 0.11.2
- **Python version**:  3.9.15
- **Operating system**: 12.6.1

### What is the current behavior?

#1670 raises an error with a circuit and split registers as follows.

```python
from qiskit import QuantumCircuit, ClassicalRegister
from qiskit.primitives import Sampler as RefSampler
from qiskit_aer.primitives import Sampler as AerSampler

qc = QuantumCircuit(2)
cr1 = ClassicalRegister(1, 'cr1')
cr2 = ClassicalRegister(1, 'cr2')
qc.add_register(cr1)
qc.add_register(cr2)
qc.measure(0, 0)
qc.measure(1, 1)

for sampler in [RefSampler(), AerSampler()]:
    print(sampler.run(qc, shots=100).result())
```

aer 0.11.1
```
<qiskit.primitives.sampler.Sampler object at 0x11b93abb0>
SamplerResult(quasi_dists=[{0: 1.0, 1: 0.0, 2: 0.0, 3: 0.0}], metadata=[{'shots': 100}])

<qiskit_aer.primitives.sampler.Sampler object at 0x11b93ab80>
SamplerResult(quasi_dists=[{0: 1.0}], metadata=[{'shots': 100, 'simulator_metadata': {'parallel_state_update': 1, 'parallel_shots': 1, 'sample_measure_time': 9.0047e-05, 'noise': 'ideal', 'batched_shots_optimization': False, 'remapped_qubits': False, 'device': 'CPU', 'active_input_qubits': [0, 1], 'measure_sampling': True, 'num_clbits': 2, 'input_qubit_map': [[1, 1], [0, 0]], 'num_qubits': 2, 'method': 'stabilizer', 'fusion': {'enabled': False}}}])
```

aer 0.11.2
```
<qiskit.primitives.sampler.Sampler object at 0x113c32dc0>
SamplerResult(quasi_dists=[{0: 1.0, 1: 0.0, 2: 0.0, 3: 0.0}], metadata=[{'shots': 100}])

<qiskit_aer.primitives.sampler.Sampler object at 0x113c32e20>
Traceback (most recent call last):
  File "/Users/ima/tasks/2_2022/qiskit/aer/tmp/split_cr.py", line 17, in <module>
    print(sampler.run(qc, shots=100).result())
  File "/Users/ima/envs/dev39/lib/python3.9/site-packages/qiskit/primitives/primitive_job.py", line 50, in result
    return self._future.result()
  File "/usr/local/Cellar/python@3.9/3.9.15/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/Cellar/python@3.9/3.9.15/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/local/Cellar/python@3.9/3.9.15/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/ima/envs/dev39/lib/python3.9/site-packages/qiskit_aer/primitives/sampler.py", line 138, in _call
    QuasiDistribution(
  File "/Users/ima/envs/dev39/lib/python3.9/site-packages/qiskit/result/distributions/quasi.py", line 71, in __init__
    raise ValueError(
ValueError: The input keys are not a valid string format, must either be a hex string prefixed by '0x' or a binary string optionally prefixed with 0b
```

### What is the expected behavior?

No error

### Suggested solutions

The main reason is Terra's `QuasiDistribution` cannot accept bitstrings with whitespaces due to split registers.
There are three opitions.

1. Reverts #1670
2. Revises `QuasiDistribution` to accept bitstrings with white spaces
3. Removes white spaces from bitstrings as follows.
https://github.com/Qiskit/qiskit-aer/blob/0f98dd476ab974c69e6d2af371a8bdb301758f64/qiskit_aer/primitives/sampler.py#L139
```python
{k.replace(" ", ""): v / shots for k, v in counts.items()},
```

**Comment by ikkoham** [comment]
Thank you. I'll fix this until next release (0.12).
