### ISSUE TITLE
Fresh python and qiskit install leads to DLL load fail errors when running the example script

### ISSUE THREAD

**Issue by garymooney** [Qiskit/qiskit-aer#1687]
### Informations

- **Qiskit Aer version**: 0.11.2
- **Python version**: 3.11.1
- **Operating system**: Windows 10 Pro

### What is the current behavior?
The following error occurs when importing AerSimulator from qiskit_aer.

> Traceback (most recent call last):
>   File "C:\Work\projects\testing aer\test_aer.py", line 3, in <module>
>     from qiskit_aer import AerSimulator
>   File "C:\Work\projects\testing aer\venv-qiskit-0.39.4\Lib\site-packages\qiskit_aer\__init__.py", line 65, in <module>
>     from .aerprovider import AerProvider
>   File "C:\Work\projects\testing aer\venv-qiskit-0.39.4\Lib\site-packages\qiskit_aer\aerprovider.py", line 19, in <module>
>     from .backends.aer_simulator import AerSimulator
>   File "C:\Work\projects\testing aer\venv-qiskit-0.39.4\Lib\site-packages\qiskit_aer\backends\__init__.py", line 17, in <module>
>     from .aer_simulator import AerSimulator
>   File "C:\Work\projects\testing aer\venv-qiskit-0.39.4\Lib\site-packages\qiskit_aer\backends\aer_simulator.py", line 30, in <module>
>     from .controller_wrappers import aer_controller_execute
> ImportError: DLL load failed while importing controller_wrappers: The specified module could not be found.

### Steps to reproduce the problem
1. Install Python
2. `python -m venv myenv`
3. `myenv\Scripts\activate.bat`
4. `pip install qiskit`
5. `python test_aer.py` where test_aer.py is the example from [README.md](https://github.com/Qiskit/qiskit-aer#readme):

```
import qiskit
from qiskit import IBMQ
from qiskit_aer import AerSimulator

circ = qiskit.QuantumCircuit(3)
circ.h(0)
circ.cx(0, 1)
circ.cx(1, 2)
circ.measure_all()

aersim = AerSimulator()

result_ideal = qiskit.execute(circ, aersim).result()
counts_ideal = result_ideal.get_counts(0)
print('Counts(ideal):', counts_ideal)

provider = IBMQ.load_account()
backend = provider.get_backend('ibmq_athens')
aersim_backend = AerSimulator.from_backend(backend)

result_noise = qiskit.execute(circ, aersim_backend).result()
counts_noise = result_noise.get_counts(0)

print('Counts(noise):', counts_noise)
```

### What is the expected behavior?
It should run with no errors. I just want to use the Aer noisy simulator with the latest version of qiskit.

**Comment by garymooney** [comment]
I read the qiskit-aer 0.11.2 supported python version wrong. I uninstalled Python 3.11.1 and installed Python 3.11 and it seems to have fixed my issue.
