### ISSUE TITLE
Building from sdist doesn't work in a venv

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit-aer#172]
### Informations

- **Qiskit Aer version**: master
- **Python version**: all
- **Operating system**: all

### What is the current behavior?

Pip installing the repo from master doesn't work when inside of a venv. When the build process starts building the wheel it attempts to run cython and it fails to import despite cython being installed in the venv and working properly inside the venv. The error looks like:

```
CMake Error at /tmp/pip-build-env-snnjnsy2/overlay/lib/python3.7/site-packages/skbuild/resources/cmake/FindCython.cmake:64 (message):
    Command "/tmp/aer-test/bin/cython;--version" failed with output:
  
    Traceback (most recent call last):
  
      File "/tmp/aer-test/bin/cython", line 6, in <module>
        from Cython.Compiler.Main import setuptools_main
  
    ModuleNotFoundError: No module named 'Cython'
  
  Call Stack (most recent call first):
    qiskit/providers/aer/backends/wrappers/CMakeLists.txt:4 (find_package)
```

The full output from the build process is:

```
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting numpy>=1.13 (from qiskit-aer==0.2.0)
  Downloading https://files.pythonhosted.org/packages/bb/76/24e9f32c78e6f6fb26cf2596b428f393bf015b63459468119f282f70a7fd/numpy-1.16.3-cp37-cp37m-manylinux1_x86_64.whl (17.3MB)
     |████████████████████████████████| 17.3MB 5.4MB/s 
Building wheels for collected packages: qiskit-aer
  Building wheel for qiskit-aer (PEP 517) ... error
  ERROR: Complete output from command /tmp/aer-test/bin/python3 /tmp/aer-test/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmp6qzv7kw4:
  ERROR: Not searching for unused variables given on the command line.
  -- The C compiler identification is GNU 8.3.0
  -- Check for working C compiler: /usr/bin/gcc
  -- Check for working C compiler: /usr/bin/gcc -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- The CXX compiler identification is GNU 8.3.0
  -- Check for working CXX compiler: /usr/bin/c++
  -- Check for working CXX compiler: /usr/bin/c++ -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Configuring done
  -- Generating done
  -- Build files have been written to: /tmp/pip-req-build-07weglrs/_cmake_test_compile/build
  -- The CXX compiler identification is GNU 8.3.0
  -- The C compiler identification is GNU 8.3.0
  -- Check for working CXX compiler: /usr/bin/c++
  -- Check for working CXX compiler: /usr/bin/c++ -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Check for working C compiler: /usr/bin/gcc
  -- Check for working C compiler: /usr/bin/gcc -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Performing Test flag_supported
  -- Performing Test flag_supported - Success
  -- Performing Test flag_supported
  -- Performing Test flag_supported - Success
  -- Performing Test flag_supported
  -- Performing Test flag_supported - Success
  -- Performing Test flag_supported
  -- Performing Test flag_supported - Success
  -- Performing Test flag_supported
  -- Performing Test flag_supported - Success
  -- Performing Test flag_supported
  -- Performing Test flag_supported - Success
  -- Performing Test flag_supported
  -- Performing Test flag_supported - Success
  -- Performing Test flag_supported
  -- Performing Test flag_supported - Success
  -- Performing Test flag_supported
  -- Performing Test flag_supported - Success
  -- Performing Test flag_supported
  -- Performing Test flag_supported - Success
  -- Performing Test flag_supported
  -- Performing Test flag_supported - Success
  OpenMP found!
  -- nlohmann include dir: /tmp/pip-req-build-07weglrs/src/third-party/headers
  -- Looking for pthread.h
  -- Looking for pthread.h - found
  -- Looking for pthread_create
  -- Looking for pthread_create - not found
  -- Looking for pthread_create in pthreads
  -- Looking for pthread_create in pthreads - not found
  -- Looking for pthread_create in pthread
  -- Looking for pthread_create in pthread - found
  -- Found Threads: TRUE
  -- Looking for OpenBLAS library...
  BLAS: /usr/lib/libopenblas.so
  -- Found PythonInterp: /tmp/aer-test/bin/python3 (found version "3.7.3")
  -- Found PythonLibs: /usr/lib/libpython3.7m.so (found version "3.7.3")
  -c:42: DeprecationWarning: SO is deprecated, use EXT_SUFFIX
  CMake Error at /tmp/pip-build-env-snnjnsy2/overlay/lib/python3.7/site-packages/skbuild/resources/cmake/FindCython.cmake:64 (message):
    Command "/tmp/aer-test/bin/cython;--version" failed with output:
  
    Traceback (most recent call last):
  
      File "/tmp/aer-test/bin/cython", line 6, in <module>
        from Cython.Compiler.Main import setuptools_main
  
    ModuleNotFoundError: No module named 'Cython'
  
  Call Stack (most recent call first):
    qiskit/providers/aer/backends/wrappers/CMakeLists.txt:4 (find_package)
  
  
  -- Found Cython: /tmp/aer-test/bin/cython
  Clang Tidy linter will be passed at build time
  -- Performing Test Weak Link MODULE -> SHARED (gnu_ld_ignore) - Success
  _modinit_prefix:PyInit_
  _modinit_prefix:PyInit_
  _modinit_prefix:PyInit_
  -- Configuring incomplete, errors occurred!
  See also "/tmp/pip-req-build-07weglrs/_skbuild/linux-x86_64-3.7/cmake-build/CMakeFiles/CMakeOutput.log".
  See also "/tmp/pip-req-build-07weglrs/_skbuild/linux-x86_64-3.7/cmake-build/CMakeFiles/CMakeError.log".
    File "/tmp/pip-build-env-snnjnsy2/overlay/lib/python3.7/site-packages/skbuild/setuptools_wrap.py", line 575, in setup
      languages=cmake_languages
    File "/tmp/pip-build-env-snnjnsy2/overlay/lib/python3.7/site-packages/skbuild/cmaker.py", line 232, in configure
      os.path.abspath(CMAKE_BUILD_DIR())))
  
  
  --------------------------------------------------------------------------------
  -- Trying "Ninja" generator
  --------------------------------
  ---------------------------
  ----------------------
  -----------------
  ------------
  -------
  --
  --
  -------
  ------------
  -----------------
  ----------------------
  ---------------------------
  --------------------------------
  -- Trying "Ninja" generator - success
  --------------------------------------------------------------------------------
  
  Traceback (most recent call last):
  
  An error occurred while configuring with CMake.
    Command:
      "cmake" "/tmp/pip-req-build-07weglrs" "-G" "Ninja" "-DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-req-build-07weglrs/_skbuild/linux-x86_64-3.7/cmake-install" "-DPYTHON_EXECUTABLE:FILEPATH=/tmp/aer-test/bin/python3" "-DPYTHON_VERSION_STRING:STRING=3.7.3" "-DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.7m" "-DPYTHON_LIBRARY:FILEPATH=/usr/lib/libpython3.7m.so" "-DSKBUILD:BOOL=TRUE" "-DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-snnjnsy2/overlay/lib/python3.7/site-packages/skbuild/resources/cmake" "-DCMAKE_BUILD_TYPE:STRING=Release"
    Source directory:
      /tmp/pip-req-build-07weglrs
    Working directory:
      /tmp/pip-req-build-07weglrs/_skbuild/linux-x86_64-3.7/cmake-build
  Please see CMake's output for more information.
  ----------------------------------------
  ERROR: Failed building wheel for qiskit-aer
  Running setup.py clean for qiskit-aer
Failed to build qiskit-aer
ERROR: Could not build wheels for qiskit-aer which use PEP 517 and cannot be installed directly
```

### Steps to reproduce the problem

Assuming openblas is installed in the proper place on your system:

1. `virtualenv test`
2. `test/bin/pip install Cython`
3. `test/bin/pip install git+https://github.com/Qiskit/qiskit-aer.git`

### What is the expected behavior?

The package is able to be built from the sdist successfully in the venv instead of failing to import cython.

### Suggested solutions

Fix the build process so this works inside a virtualenv. If building via sdist only works outside of a venv this isn't useful and will not be usable by a large number of people.

**Comment by atilag** [comment]
Just for th record, this was an already know problem with pip >= 19. I filled an issue about it here: https://github.com/pypa/pip/issues/6360

**Comment by atilag** [comment]
@mtreinish did it work by downgrading pip to 18 ?

**Comment by mtreinish** [comment]
On linux and osx it worked. But I still can't it to build from sdist on windows. Also forcing pip 18 isn't really a solution, there are some environments where this isn't directly controllable (see all my attempts to get appveyor to downgrade pip on: https://github.com/Qiskit/qiskit-ignis/pull/162 ) or inside cibuildwheel on #168

**Comment by mtreinish** [comment]
That being said cmake still seems to fail during osx and linux builds with pip 18.1, but the installation still succeeds: https://travis-ci.com/Qiskit/qiskit-ignis/jobs/196490145#L5018 I'm not sure exactly what that means. But debugging the build process is next to impossible when there are almost 5k lines of warnings (or errors) emitted during the build process.

**Comment by atilag** [comment]
Building from sdist should be working using latest master. There's nothing we can do about the pip issue, though. So pip 18 is required.

**Comment by mtreinish** [comment]
This shouldn't be closed, we need to document all of this behavior. People are going to be able to run `pip install qiskit-aer` on environments which we don't publish wheels for. There have been several bugs for 0.1.1 already opened on this topic. We need to make it very clear how people can build aer via pip and have somewhere we can point them too when people inevitably complain that they can't install aer 0.2.0 on their system.

**Comment by atilag** [comment]
I do agree that we need better documentation about the building experience in Windows, but we just can't support all possible enviroments. Most of the time because of Python ecosystem constraints. Building will inevitable require reading the CONTRIBUTING guide and install all the pre-requisites.
Anyway, we might be supporting about 95% of users with our prebuilt wheels, so I'd not expect too many users trying to build from sdist (but from the repo).

**Comment by atilag** [comment]
I have filed a new issue (#193) for tracking the specific problem with pip 19

**Comment by atilag** [comment]
Putting this on hold until pip solves the problem.

**Comment by jwoehr** [comment]
Thanks for great bug report, it saved me from asking a FAQ on qiskit slack.

But I still get the exact reported error on Mac OS x 10.14.5 with pip 18.0 or pip 18.1 when trying to do `pip install -e .` for Aer or `./setup.py bdist_wheel`. My source is up-to-date with Aer `master` branch. 

Any tips or pointers?

**Comment by atilag** [comment]
pip 19.3.1 has finally fixed the problem. So we can close this issue.
