### ISSUE TITLE
Test failures with 0.12.0 (0.11.2 passes)

### ISSUE THREAD

**Issue by thesamesam** [Qiskit/qiskit-aer#1742]
### Informations

- **Qiskit Aer version**: 0.12.0
- **Python version**: Python 3.9.16
- **Operating system**: Gentoo Linux (I'm the maintainer of its package)

### What is the current behavior?

Various tests seem to fail with qiskit-aer-0.12.0, while qiskit-0.11.2 passed all its tests at the time of release and still passes them when I check now, which suggests it's not an environment issue.

The failures all look identical:
```
______________________________________________________________ TestNoiseModel.test_noise_model_from_lagos_v2 ______________________________________________________________
'NoneType' object is not iterable

During handling of the above exception, another exception occurred:
NOTE: Incompatible Exception Representation, displaying natively:

testtools.testresult.real._StringException: Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/qiskit-aer-0.12.0/work/qiskit-aer-0.12.0/test/terra/noise/test_noise_model.py", line 252, in test_noise_model_from_lagos_v2
    result = AerSimulator().run(circ, noise_model=noise_model).result()
  File "/var/tmp/portage/dev-python/qiskit-aer-0.12.0/work/qiskit-aer-0.12.0-python3_9/install/usr/lib/python3.9/site-packages/qiskit_aer/jobs/utils.py", line 41, in _wrapper
    return func(self, *args, **kwargs)
  File "/var/tmp/portage/dev-python/qiskit-aer-0.12.0/work/qiskit-aer-0.12.0-python3_9/install/usr/lib/python3.9/site-packages/qiskit_aer/jobs/aerjob.py", line 106, in result
    return self._future.result(timeout=timeout)
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/var/tmp/portage/dev-python/qiskit-aer-0.12.0/work/qiskit-aer-0.12.0-python3_9/install/usr/lib/python3.9/site-packages/qiskit_aer/backends/aerbackend.py", line 438, in _execute_circuits_job
    output = self._execute_circuits(aer_circuits, noise_model, config)
  File "/var/tmp/portage/dev-python/qiskit-aer-0.12.0/work/qiskit-aer-0.12.0-python3_9/install/usr/lib/python3.9/site-packages/qiskit_aer/backends/aer_simulator.py", line 736, in _execute_circuits
    ret = cpp_execute_circuits(self._controller, aer_circuits, noise_model, config)
  File "/var/tmp/portage/dev-python/qiskit-aer-0.12.0/work/qiskit-aer-0.12.0-python3_9/install/usr/lib/python3.9/site-packages/qiskit_aer/backends/backend_utils.py", line 137, in cpp_execute_circuits
    return controller.execute(aer_circuits, noise_model, config)
ValueError: Invalid noise_params JSON: not an object.
```

The full log is available here:  [build.log.gz](https://github.com/Qiskit/qiskit-aer/files/10939181/build.log.gz)

Let me know if I can give more information.

### Steps to reproduce the problem

1. Build qiskit-aer-0.12.0
2. Try to run tests with `pytest`
3. Observe long list of new failures

I can try cook up a Gentoo Dockerfile to reproduce if needed.

### What is the expected behavior?

All tests pass.

### Suggested solutions

N/A

**Comment by hhorii** [comment]
Thank you for your report. We are uinsg `stestr` and it does not report the above error.
Could you test `stestr run --slowest` and tell me whether you encounter the same errors?

**Comment by hhorii** [comment]
BTW, I have tested with `pytest` on my linux env (Ubuntu) but was not able to reproduce the above error.

**Comment by hhorii** [comment]
Let me close this issue because no response in a month. Feel free to reopen this or open new issue if a problem remains.

**Comment by thesamesam** [comment]
Okay, I bisected, and I came up with:

commit 5e5f22cc638a288ad2a35be882f27aaed04d1a8f
Author: Hiroshi Horii <hhorii@users.noreply.github.com>
Date:   Thu Mar 9 01:21:15 2023 +0900

    Simulate `QuantumCircuit` without QObj (#1717)

    With this commit, Aer simulates `QuantumCircuit` without converting it to QObj.
    Previously, QObj is generated from `QuantumCircuit` objects in python, and then
    C++ parses QObj to construct own circuit representation `AER::Circuit` for simulation.
    Now, Aer binds this `AER::Circuit` with a python class `AerCircuit` and directly
    generates from `QuantumCircuit` to `AerCircuit`. In addition, configuration for simulation
    is changed from json to `AerConfig` that be bound to `AER::Config`.
    This commit will improve performance of low-qubit simulation without any modification
    of application codes.

cc @hhorii

Any ideas?

**Comment by thesamesam** [comment]
@hhorii I still seem to get these with 0.12.2. Does the bisect from above help? Thanks.

**Comment by mgorny** [comment]
Ping.

**Comment by mgorny** [comment]
So I've been able to determine that nlohmann_json is to blame. 3.10.2 is the newest version that "works", with 3.10.3 qiskit-aer doesn't compile, and with 3.10.4+ it fails.

**Comment by iyanmv** [comment]
Same issue with Qiskit Aer 0.16 and nlohmann-json 3.11.3

**Comment by iyanmv** [comment]
I tested both with `pytest` and `stestr run --slowest` as it is run in GitHub Actions.

```
======
Totals
======
Ran: 2675 tests in 186.7343 sec.
 - Passed: 2459
 - Skipped: 15
 - Expected Fail: 0
 - Unexpected Success: 0
 - Failed: 196
Sum of execute time for each test: 873.1687 sec.
```

**Comment by iyanmv** [comment]
To be fair, I got the following warning when compiling the wheel package:

```
-- nlohmann_json 3.1.1 NOT found! Looking for any other version available.
-- Found nlohmann_json: /usr/share/cmake/nlohmann_json/nlohmann_jsonConfig.cmake (found version "3.11.3")
-- nlohmann_json version found: 3.11.3. WARNING: This version may not work!!!
-- Using system-provided nlohmann_json library
```

But that release is almost 7 years old!
