### ISSUE TITLE
EstimatorV2 extended_stabilizer fails" invalid instructions {"instructions": {save_expval}}

### ISSUE THREAD

**Issue by zlatko-minev** [Qiskit/qiskit-aer#2121]
### Informations

- **Qiskit Aer version**: 0.14.1
- **Python version**: 3.11
- **Operating system**: Mac

### What is the current behavior?

Can't run extended stabilizer with Estimator, see code:

### Steps to reproduce the problem
```python
from qiskit_aer.primitives import EstimatorV2 
qc = QuantumCircuit(2)
qc.sx(0)
qc.cx(0,1)
obs = ['ZI']

options = {
    "backend_options": {  
        "method": "extended_stabilizer",
    }
}
estimator = EstimatorV2(options=options)
print(estimator._backend)
job = estimator.run([(qc, obs)])

```
Return
```python
AerSimulator('aer_simulator_extended_stabilizer')
Simulation failed and returned the following error message:
ERROR:  [Experiment 0] Circuit circuit-394 contains invalid instructions {"instructions": {save_expval}} for "extended_stabilizer" method.Circuit circuit-394 contains invalid parameters  for "extended_stabilizer" method.
```

### What is the expected behavior?
Should run extended stabilizer with Estimator.

### Suggested solutions
NA

**Comment by kevinsung** [comment]
So strange. When I run the code in @zlatko-minev 's repro, I get a different error. I'm using the same Aer version and Python 0.14.1, but my OS is Fedora Linux 40.

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[1], [line 13](vscode-notebook-cell:?execution_count=1&line=13)
      [6](vscode-notebook-cell:?execution_count=1&line=6) obs = ['ZI']
      [8](vscode-notebook-cell:?execution_count=1&line=8) options = {
      [9](vscode-notebook-cell:?execution_count=1&line=9)     "backend_options": {  
     [10](vscode-notebook-cell:?execution_count=1&line=10)         "method": "extended_stabilizer",
     [11](vscode-notebook-cell:?execution_count=1&line=11)     }
     [12](vscode-notebook-cell:?execution_count=1&line=12) }
---> [13](vscode-notebook-cell:?execution_count=1&line=13) estimator = EstimatorV2(options=options)
     [14](vscode-notebook-cell:?execution_count=1&line=14) print(estimator._backend)
     [15](vscode-notebook-cell:?execution_count=1&line=15) job = estimator.run([(qc, obs)])

File ~/.pyenv/versions/documentation/lib/python3.11/site-packages/qiskit_aer/primitives/estimator_v2.py:74, in EstimatorV2.__init__(self, options)
     [72](https://vscode-remote+ssh-002dremote-002bwork-002dlaptop.vscode-resource.vscode-cdn.net/home/kevinsung/projects/documentation/scratch/~/.pyenv/versions/documentation/lib/python3.11/site-packages/qiskit_aer/primitives/estimator_v2.py:72) self._options = Options(**options) if options else Options()
     [73](https://vscode-remote+ssh-002dremote-002bwork-002dlaptop.vscode-resource.vscode-cdn.net/home/kevinsung/projects/documentation/scratch/~/.pyenv/versions/documentation/lib/python3.11/site-packages/qiskit_aer/primitives/estimator_v2.py:73) method = "density_matrix" if "noise_model" in self.options.backend_options else "automatic"
---> [74](https://vscode-remote+ssh-002dremote-002bwork-002dlaptop.vscode-resource.vscode-cdn.net/home/kevinsung/projects/documentation/scratch/~/.pyenv/versions/documentation/lib/python3.11/site-packages/qiskit_aer/primitives/estimator_v2.py:74) self._backend = AerSimulator(method=method, **self.options.backend_options)

TypeError: qiskit_aer.backends.aer_simulator.AerSimulator() got multiple values for keyword argument 'method'
```

**Comment by doichanj** [comment]
I found `save_expval` is disabled because there are some issue in implementation of `save_expval` of extended stabilizer.

https://github.com/Qiskit/qiskit-aer/blob/83d679efd510e911920e2655936e15fefd9d4392/src/simulators/extended_stabilizer/extended_stabilizer_state.hpp#L401-L405

**Comment by doichanj** [comment]
> So strange. When I run the code in @zlatko-minev 's repro, I get a different error. I'm using the same Aer version and Python 0.14.1, but my OS is Fedora Linux 40.
> 
> ```
> Traceback (most recent call last):
>   File "/home/kevinsung/projects/documentation/test.py", line 13, in <module>
>     estimator = EstimatorV2(options=options)
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/kevinsung/.pyenv/versions/documentation/lib/python3.11/site-packages/qiskit_aer/primitives/estimator_v2.py", line 74, in __init__
>     self._backend = AerSimulator(method=method, **self.options.backend_options)
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> TypeError: qiskit_aer.backends.aer_simulator.AerSimulator() got multiple values for keyword argument 'method'
> ```

This is fixed by PR #2120

**Comment by doichanj** [comment]
I'm feeling difficulty to solve expval bug in extended stabilizer, so I think I will not include fix in Aer 014.2

**Comment by zlatko-minev** [comment]
Thank you for trying. Can you add a little more on what the issue is? That's tricky to resolve. 

I hope somebody else here might be able to contribute as well.

The thing is that we're increasingly moving to using the estimator class and so this is now the default preferred pathway.

**Comment by doichanj** [comment]
I opened PR #2161 for this issue.
I'm fixing bugs in save_expval and now it works for clifford circuits
I think it is not easy because of accuracy for non-clifford circuits

**Comment by zlatko-minev** [comment]
Thanks! What do you mean by accuracy for non Clifford’s? Just the number of t gates and cost associated in memory with that Sent from my iPhoneOn Jun 3, 2024, at 5:57 AM, Jun Doi ***@***.***> wrote:﻿
I opened PR #2161 for this issue.
I'm fixing bugs in save_expval and now it works for clifford circuits
I think it is not easy because of accuracy for non-clifford circuits

**Comment by doichanj** [comment]
It seems the estimation is unstable for non clifford circuits that causes wrong expectation values

**Comment by zlatko-minev** [comment]
You mean as a function of the truncation?And if a user increases the truncation it converges.  On Jun 3, 2024, at 10:31 PM, Jun Doi ***@***.***> wrote:﻿
It seems the estimation is unstable for non clifford circuits that causes wrong expectation values
