### ISSUE TITLE
Fix sphinx-warnings in API documentation build

### ISSUE THREAD

**Issue by chriseclectic** [Qiskit/qiskit-aer#434]
Fix the warnings that are showing in the build log of the API documentation.

**Comment by mtreinish** [comment]
Building locally I get 71 warnings according to sphinx, looking at the output these are:

```
WARNING: failed to import NoiseModel.QASMSIMULATOR_BASIS_GATES
WARNING: autodoc: failed to import attribute 'NoiseModel.QASMSIMULATOR_BASIS_GATES' from module 'qiskit.providers.aer.noise'; the following exception was raised:
Traceback (most recent call last):
  File "/home/mtreinish/git/qiskit/qiskit-aer/.tox/docs/lib/python3.7/site-packages/sphinx/util/inspect.py", line 230, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: type object 'NoiseModel' has no attribute 'QASMSIMULATOR_BASIS_GATES'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mtreinish/git/qiskit/qiskit-aer/.tox/docs/lib/python3.7/site-packages/sphinx/ext/autodoc/importer.py", line 71, in import_object
    obj = attrgetter(obj, attrname)
  File "/home/mtreinish/git/qiskit/qiskit-aer/.tox/docs/lib/python3.7/site-packages/sphinx/ext/autodoc/__init__.py", line 226, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/home/mtreinish/git/qiskit/qiskit-aer/.tox/docs/lib/python3.7/site-packages/sphinx/ext/autodoc/__init__.py", line 1501, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/home/mtreinish/git/qiskit/qiskit-aer/.tox/docs/lib/python3.7/site-packages/sphinx/util/inspect.py", line 246, in safe_getattr
    raise AttributeError(name)
AttributeError: QASMSIMULATOR_BASIS_GATES

/home/mtreinish/git/qiskit/qiskit-aer/docs/stubs/qiskit.providers.aer.AerError.rst:2: WARNING: duplicate object description of qiskit.providers.aer.AerError, other instance in api/qiskit.providers.aer.AerError, use :noindex: for one of them
/home/mtreinish/git/qiskit/qiskit-aer/docs/stubs/qiskit.providers.aer.AerError.rst:10: WARNING: duplicate object description of qiskit.providers.aer.AerError.with_traceback, other instance in api/qiskit.providers.aer.AerError, use :noindex: for one of them
/home/mtreinish/git/qiskit/qiskit-aer/docs/stubs/qiskit.providers.aer.AerJob.rst:2: WARNING: duplicate object description of qiskit.providers.aer.AerJob, other instance in api/qiskit.providers.aer.AerJob, use :noindex: for one of them
/home/mtreinish/git/qiskit/qiskit-aer/docs/stubs/qiskit.providers.aer.AerJob.rst:7: WARNING: duplicate object description of qiskit.providers.aer.AerJob._executor, other instance in api/qiskit.providers.aer.AerJob, use :noindex: for one of them
/home/mtreinish/git/qiskit/qiskit-aer/docs/stubs/qiskit.providers.aer.AerJob.backend.rst:2: WARNING: duplicate object description of qiskit.providers.aer.AerJob.backend, other instance in api/qiskit.providers.aer.AerJob, use :noindex: for one of them
/home/mtreinish/git/qiskit/qiskit-aer/docs/stubs/qiskit.providers.aer.AerJob.cancel.rst:2: WARNING: duplicate object description of qiskit.providers.aer.AerJob.cancel, other instance in api/qiskit.providers.aer.AerJob, use :noindex: for one of them
/home/mtreinish/git/qiskit/qiskit-aer/docs/stubs/qiskit.providers.aer.AerJob.job_id.rst:2: WARNING: duplicate object description of qiskit.providers.aer.AerJob.job_id, other instance in api/qiskit.providers.aer.AerJob, use :noindex: for one of them
/home/mtreinish/git/qiskit/qiskit-aer/docs/stubs/qiskit.providers.aer.AerJob.qobj.rst:2: WARNING: duplicate object description of qiskit.providers.aer.AerJob.qobj, other instance in api/qiskit.providers.aer.AerJob, use :noindex: for one of them
/home/mtreinish/git/qiskit/qiskit-aer/docs/stubs/qiskit.providers.aer.AerJob.result.rst:2: WARNING: duplicate object description of qiskit.providers.aer.AerJob.result, other instance in api/qiskit.providers.aer.AerJob, use :noindex: for one of them
/home/mtreinish/git/qiskit/qiskit-aer/docs/stubs/qiskit.providers.aer.AerJob.status.rst:2: WARNING: duplicate object description of qiskit.providers.aer.AerJob.status, other instance in api/qiskit.providers.aer.AerJob, use :noindex: for one of them
/home/mtreinish/git/qiskit/qiskit-aer/docs/stubs/qiskit.providers.aer.AerJob.submit.rst:2: WARNING: duplicate object description of qiskit.providers.aer.AerJob.submit, other instance in api/qiskit.providers.aer.AerJob, use :noindex: for one of them
/home/mtreinish/git/qiskit/qiskit-aer/docs/stubs/qiskit.providers.aer.AerProvider.rst:2: WARNING: duplicate object description of qiskit.providers.aer.AerProvider, other instance in api/qiskit.providers.aer.AerProvider, use :noindex: for one of them
/home/mtreinish/git/qiskit/qiskit-aer/docs/stubs/qiskit.providers.aer.AerProvider.backends.rst:2: WARNING: duplicate object description of qiskit.providers.aer.AerProvider.backends, other instance in api/qiskit.providers.aer.AerProvider, use :noindex: for one of them
/home/mtreinish/git/qiskit/qiskit-aer/docs/stubs/qiskit.providers.aer.AerProvider.get_backend.rst:2: WARNING: duplicate object description of qiskit.providers.aer.AerProvider.get_backend, other instance in api/qiskit.providers.aer.AerProvider, use :noindex: for one of them
/home/mtreinish/git/qiskit/qiskit-aer/docs/stubs/qiskit.providers.aer.QasmSimulator.rst:2: WARNING: duplicate object description of qiskit.providers.aer.QasmSimulator, other instance in api/qiskit.providers.aer.QasmSimulator, use :noindex: for one of them
/home/mtreinish/git/qiskit/qiskit-aer/docs/stubs/qiskit.providers.aer.QasmSimulator.DEFAULT_CONFIGURATION.rst:2: WARNING: duplicate object description of qiskit.providers.aer.QasmSimulator.DEFAULT_CONFIGURATION, other instance in api/qiskit.providers.aer.QasmSimulator, use :noindex: for one of them
/home/mtreinish/git/qiskit/qiskit-aer/docs/stubs/qiskit.providers.aer.QasmSimulator.MAX_QUBIT_MEMORY.rst:2: WARNING: duplicate object description of qiskit.providers.aer.QasmSimulator.MAX_QUBIT_MEMORY, other instance in api/qiskit.providers.aer.QasmSimulator, use :noindex: for one of them
/home/mtreinish/git/qiskit/qiskit-aer/docs/stubs/qiskit.providers.aer.QasmSimulator.configuration.rst:2: WARNING: duplicate object description of qiskit.providers.aer.QasmSimulator.configuration, other instance in api/qiskit.providers.aer.QasmSimulator, use :noindex: for one of them
/home/mtreinish/git/qiskit/qiskit-aer/docs/stubs/qiskit.providers.aer.QasmSimulator.name.rst:2: WARNING: duplicate object description of qiskit.providers.aer.QasmSimulator.name, other instance in api/qiskit.providers.aer.QasmSimulator, use :noindex: for one of them
/home/mtreinish/git/qiskit/qiskit-aer/docs/stubs/qiskit.providers.aer.QasmSimulator.properties.rst:2: WARNING: duplicate object description of qiskit.providers.aer.QasmSimulator.properties, other instance in api/qiskit.providers.aer.QasmSimulator, use :noindex: for one of them
/home/mtreinish/git/qiskit/qiskit-aer/docs/stubs/qiskit.providers.aer.QasmSimulator.provider.rst:2: WARNING: duplicate object description of qiskit.providers.aer.QasmSimulator.provider, other instance in api/qiskit.providers.aer.QasmSimulator, use :noindex: for one of them
/home/mtreinish/git/qiskit/qiskit-aer/docs/stubs/qiskit.providers.aer.QasmSimulator.run.rst:2: WARNING: duplicate object description of qiskit.providers.aer.QasmSimulator.run, other instance in api/qiskit.providers.aer.QasmSimulator, use :noindex: for one of them
/home/mtreinish/git/qiskit/qiskit-aer/docs/stubs/qiskit.providers.aer.QasmSimulator.status.rst:2: WARNING: duplicate object description of qiskit.providers.aer.QasmSimulator.status, other instance in api/qiskit.providers.aer.QasmSimulator, use :noindex: for one of them
/home/mtreinish/git/qiskit/qiskit-aer/docs/stubs/qiskit.providers.aer.QasmSimulator.version.rst:2: WARNING: duplicate object description of qiskit.providers.aer.QasmSimulator.version, other instance in api/qiskit.providers.aer.QasmSimulator, use :noindex: for one of them
/home/mtreinish/git/qiskit/qiskit-aer/docs/stubs/qiskit.providers.aer.StatevectorSimulator.rst:2: WARNING: duplicate object description of qiskit.providers.aer.StatevectorSimulator, other instance in api/qiskit.providers.aer.StatevectorSimulator, use :noindex: for one of them
/home/mtreinish/git/qiskit/qiskit-aer/docs/stubs/qiskit.providers.aer.StatevectorSimulator.DEFAULT_CONFIGURATION.rst:2: WARNING: duplicate object description of qiskit.providers.aer.StatevectorSimulator.DEFAULT_CONFIGURATION, other instance in api/qiskit.providers.aer.StatevectorSimulator, use :noindex: for one of them
/home/mtreinish/git/qiskit/qiskit-aer/docs/stubs/qiskit.providers.aer.StatevectorSimulator.MAX_QUBIT_MEMORY.rst:2: WARNING: duplicate object description of qiskit.providers.aer.StatevectorSimulator.MAX_QUBIT_MEMORY, other instance in api/qiskit.providers.aer.StatevectorSimulator, use :noindex: for one of them
/home/mtreinish/git/qiskit/qiskit-aer/docs/stubs/qiskit.providers.aer.StatevectorSimulator.configuration.rst:2: WARNING: duplicate object description of qiskit.providers.aer.StatevectorSimulator.configuration, other instance in api/qiskit.providers.aer.StatevectorSimulator, use :noindex: for one of them
/home/mtreinish/git/qiskit/qiskit-aer/docs/stubs/qiskit.providers.aer.StatevectorSimulator.name.rst:2: WARNING: duplicate object description of qiskit.providers.aer.StatevectorSimulator.name, other instance in api/qiskit.providers.aer.StatevectorSimulator, use :noindex: for one of them
/home/mtreinish/git/qiskit/qiskit-aer/docs/stubs/qiskit.providers.aer.StatevectorSimulator.properties.rst:2: WARNING: duplicate object description of qiskit.providers.aer.StatevectorSimulator.properties, other instance in api/qiskit.providers.aer.StatevectorSimulator, use :noindex: for one of them
/home/mtreinish/git/qiskit/qiskit-aer/docs/stubs/qiskit.providers.aer.StatevectorSimulator.provider.rst:2: WARNING: duplicate object description of qiskit.providers.aer.StatevectorSimulator.provider, other instance in api/qiskit.providers.aer.StatevectorSimulator, use :noindex: for one of them
/home/mtreinish/git/qiskit/qiskit-aer/docs/stubs/qiskit.providers.aer.StatevectorSimulator.run.rst:2: WARNING: duplicate object description of qiskit.providers.aer.StatevectorSimulator.run, other instance in api/qiskit.providers.aer.StatevectorSimulator, use :noindex: for one of them
/home/mtreinish/git/qiskit/qiskit-aer/docs/stubs/qiskit.providers.aer.StatevectorSimulator.status.rst:2: WARNING: duplicate object description of qiskit.providers.aer.StatevectorSimulator.status, other instance in api/qiskit.providers.aer.StatevectorSimulator, use :noindex: for one of them
/home/mtreinish/git/qiskit/qiskit-aer/docs/stubs/qiskit.providers.aer.StatevectorSimulator.version.rst:2: WARNING: duplicate object description of qiskit.providers.aer.StatevectorSimulator.version, other instance in api/qiskit.providers.aer.StatevectorSimulator, use :noindex: for one of them
/home/mtreinish/git/qiskit/qiskit-aer/docs/stubs/qiskit.providers.aer.UnitarySimulator.rst:2: WARNING: duplicate object description of qiskit.providers.aer.UnitarySimulator, other instance in api/qiskit.providers.aer.UnitarySimulator, use :noindex: for one of them
/home/mtreinish/git/qiskit/qiskit-aer/docs/stubs/qiskit.providers.aer.UnitarySimulator.DEFAULT_CONFIGURATION.rst:2: WARNING: duplicate object description of qiskit.providers.aer.UnitarySimulator.DEFAULT_CONFIGURATION, other instance in api/qiskit.providers.aer.UnitarySimulator, use :noindex: for one of them
/home/mtreinish/git/qiskit/qiskit-aer/docs/stubs/qiskit.providers.aer.UnitarySimulator.MAX_QUBIT_MEMORY.rst:2: WARNING: duplicate object description of qiskit.providers.aer.UnitarySimulator.MAX_QUBIT_MEMORY, other instance in api/qiskit.providers.aer.UnitarySimulator, use :noindex: for one of them
/home/mtreinish/git/qiskit/qiskit-aer/docs/stubs/qiskit.providers.aer.UnitarySimulator.configuration.rst:2: WARNING: duplicate object description of qiskit.providers.aer.UnitarySimulator.configuration, other instance in api/qiskit.providers.aer.UnitarySimulator, use :noindex: for one of them
/home/mtreinish/git/qiskit/qiskit-aer/docs/stubs/qiskit.providers.aer.UnitarySimulator.name.rst:2: WARNING: duplicate object description of qiskit.providers.aer.UnitarySimulator.name, other instance in api/qiskit.providers.aer.UnitarySimulator, use :noindex: for one of them
/home/mtreinish/git/qiskit/qiskit-aer/docs/stubs/qiskit.providers.aer.UnitarySimulator.properties.rst:2: WARNING: duplicate object description of qiskit.providers.aer.UnitarySimulator.properties, other instance in api/qiskit.providers.aer.UnitarySimulator, use :noindex: for one of them
/home/mtreinish/git/qiskit/qiskit-aer/docs/stubs/qiskit.providers.aer.UnitarySimulator.provider.rst:2: WARNING: duplicate object description of qiskit.providers.aer.UnitarySimulator.provider, other instance in api/qiskit.providers.aer.UnitarySimulator, use :noindex: for one of them
/home/mtreinish/git/qiskit/qiskit-aer/docs/stubs/qiskit.providers.aer.UnitarySimulator.run.rst:2: WARNING: duplicate object description of qiskit.providers.aer.UnitarySimulator.run, other instance in api/qiskit.providers.aer.UnitarySimulator, use :noindex: for one of them
/home/mtreinish/git/qiskit/qiskit-aer/docs/stubs/qiskit.providers.aer.UnitarySimulator.status.rst:2: WARNING: duplicate object description of qiskit.providers.aer.UnitarySimulator.status, other instance in api/qiskit.providers.aer.UnitarySimulator, use :noindex: for one of them
/home/mtreinish/git/qiskit/qiskit-aer/docs/stubs/qiskit.providers.aer.UnitarySimulator.version.rst:2: WARNING: duplicate object description of qiskit.providers.aer.UnitarySimulator.version, other instance in api/qiskit.providers.aer.UnitarySimulator, use :noindex: for one of them
/home/mtreinish/git/qiskit/qiskit-aer/docs/stubs/qiskit.providers.aer.noise.NoiseModel.rst:2: WARNING: duplicate object description of qiskit.providers.aer.noise.NoiseModel, other instance in api/qiskit.providers.aer.noise.NoiseModel, use :noindex: for one of them
/home/mtreinish/git/qiskit/qiskit-aer/docs/stubs/qiskit.providers.aer.noise.NoiseModel.add_all_qubit_quantum_error.rst:2: WARNING: duplicate object description of qiskit.providers.aer.noise.NoiseModel.add_all_qubit_quantum_error, other instance in api/qiskit.providers.aer.noise.NoiseModel, use :noindex: for one of them
/home/mtreinish/git/qiskit/qiskit-aer/docs/stubs/qiskit.providers.aer.noise.NoiseModel.add_all_qubit_readout_error.rst:2: WARNING: duplicate object description of qiskit.providers.aer.noise.NoiseModel.add_all_qubit_readout_error, other instance in api/qiskit.providers.aer.noise.NoiseModel, use :noindex: for one of them
/home/mtreinish/git/qiskit/qiskit-aer/docs/stubs/qiskit.providers.aer.noise.NoiseModel.add_basis_gates.rst:2: WARNING: duplicate object description of qiskit.providers.aer.noise.NoiseModel.add_basis_gates, other instance in api/qiskit.providers.aer.noise.NoiseModel, use :noindex: for one of them
/home/mtreinish/git/qiskit/qiskit-aer/docs/stubs/qiskit.providers.aer.noise.NoiseModel.add_nonlocal_quantum_error.rst:2: WARNING: duplicate object description of qiskit.providers.aer.noise.NoiseModel.add_nonlocal_quantum_error, other instance in api/qiskit.providers.aer.noise.NoiseModel, use :noindex: for one of them
/home/mtreinish/git/qiskit/qiskit-aer/docs/stubs/qiskit.providers.aer.noise.NoiseModel.add_quantum_error.rst:2: WARNING: duplicate object description of qiskit.providers.aer.noise.NoiseModel.add_quantum_error, other instance in api/qiskit.providers.aer.noise.NoiseModel, use :noindex: for one of them
/home/mtreinish/git/qiskit/qiskit-aer/docs/stubs/qiskit.providers.aer.noise.NoiseModel.add_readout_error.rst:2: WARNING: duplicate object description of qiskit.providers.aer.noise.NoiseModel.add_readout_error, other instance in api/qiskit.providers.aer.noise.NoiseModel, use :noindex: for one of them
/home/mtreinish/git/qiskit/qiskit-aer/docs/stubs/qiskit.providers.aer.noise.NoiseModel.as_dict.rst:2: WARNING: duplicate object description of qiskit.providers.aer.noise.NoiseModel.as_dict, other instance in api/qiskit.providers.aer.noise.NoiseModel, use :noindex: for one of them
/home/mtreinish/git/qiskit/qiskit-aer/docs/stubs/qiskit.providers.aer.noise.NoiseModel.basis_gates.rst:2: WARNING: duplicate object description of qiskit.providers.aer.noise.NoiseModel.basis_gates, other instance in api/qiskit.providers.aer.noise.NoiseModel, use :noindex: for one of them
/home/mtreinish/git/qiskit/qiskit-aer/docs/stubs/qiskit.providers.aer.noise.NoiseModel.from_dict.rst:2: WARNING: duplicate object description of qiskit.providers.aer.noise.NoiseModel.from_dict, other instance in api/qiskit.providers.aer.noise.NoiseModel, use :noindex: for one of them
/home/mtreinish/git/qiskit/qiskit-aer/docs/stubs/qiskit.providers.aer.noise.NoiseModel.noise_instructions.rst:2: WARNING: duplicate object description of qiskit.providers.aer.noise.NoiseModel.noise_instructions, other instance in api/qiskit.providers.aer.noise.NoiseModel, use :noindex: for one of them
/home/mtreinish/git/qiskit/qiskit-aer/docs/stubs/qiskit.providers.aer.noise.NoiseModel.noise_qubits.rst:2: WARNING: duplicate object description of qiskit.providers.aer.noise.NoiseModel.noise_qubits, other instance in api/qiskit.providers.aer.noise.NoiseModel, use :noindex: for one of them
/home/mtreinish/git/qiskit/qiskit-aer/docs/stubs/qiskit.providers.aer.noise.NoiseModel.reset.rst:2: WARNING: duplicate object description of qiskit.providers.aer.noise.NoiseModel.reset, other instance in api/qiskit.providers.aer.noise.NoiseModel, use :noindex: for one of them
/home/mtreinish/git/qiskit/qiskit-aer/docs/stubs/qiskit.providers.aer.noise.NoiseModel.set_x90_single_qubit_gates.rst:2: WARNING: duplicate object description of qiskit.providers.aer.noise.NoiseModel.set_x90_single_qubit_gates, other instance in api/qiskit.providers.aer.noise.NoiseModel, use :noindex: for one of them
/home/mtreinish/git/qiskit/qiskit-aer/docs/stubs/qiskit.providers.aer.noise.NoiseModel.to_dict.rst:2: WARNING: duplicate object description of qiskit.providers.aer.noise.NoiseModel.to_dict, other instance in api/qiskit.providers.aer.noise.NoiseModel, use :noindex: for one of them
/home/mtreinish/git/qiskit/qiskit-aer/docs/api/qiskit.providers.aer.AerError.rst: WARNING: document isn't included in any toctree
/home/mtreinish/git/qiskit/qiskit-aer/docs/api/qiskit.providers.aer.AerJob.rst: WARNING: document isn't included in any toctree
/home/mtreinish/git/qiskit/qiskit-aer/docs/api/qiskit.providers.aer.AerProvider.rst: WARNING: document isn't included in any toctree
/home/mtreinish/git/qiskit/qiskit-aer/docs/api/qiskit.providers.aer.QasmSimulator.rst: WARNING: document isn't included in any toctree
/home/mtreinish/git/qiskit/qiskit-aer/docs/api/qiskit.providers.aer.StatevectorSimulator.rst: WARNING: document isn't included in any toctree
/home/mtreinish/git/qiskit/qiskit-aer/docs/api/qiskit.providers.aer.UnitarySimulator.rst: WARNING: document isn't included in any toctree
/home/mtreinish/git/qiskit/qiskit-aer/docs/api/qiskit.providers.aer.backends.QasmSimulator.rst: WARNING: document isn't included in any toctree
/home/mtreinish/git/qiskit/qiskit-aer/docs/api/qiskit.providers.aer.backends.StatevectorSimulator.rst: WARNING: document isn't included in any toctree
/home/mtreinish/git/qiskit/qiskit-aer/docs/api/qiskit.providers.aer.backends.UnitarySimulator.rst: WARNING: document isn't included in any toctree
/home/mtreinish/git/qiskit/qiskit-aer/docs/api/qiskit.providers.aer.noise.NoiseModel.rst: WARNING: document isn't included in any toctree
```

Once we fix these issues we can add -W to the sphinx-build call in the tox.ini
