### ISSUE TITLE
Fail to run anything on Linux

### ISSUE THREAD

**Issue by yaelbh** [Qiskit/qiskit-aer#556]
### Informations

- **Qiskit Aer version**: master
- **Python version**: 3.6.5
- **Operating system**: Linux

### What is the current behavior?

I pulled Aer and Terra newest master branches today and have a real trouble running Aer on Linux. It compiles but when I try to run something it spends a lot of time creating a directory named .pyxbld in my home directory (??), then it complains about some "compilation error" in that new uninvited directory.

```
/home/yaelbh/.pyxbld/temp.linux-x86_64-3.6/pyrex/qiskit/providers/aer/openpulse/qutip_lite/cy/spmatfuncs.cpp:615:25: fatal error: src/zspmv.hpp: No such file or directory
compilation terminated.
/home/yaelbh/work/terra/System/qiskit/__init__.py:55: RuntimeWarning: Could not import the Aer provider from the qiskit-aer package. Install qiskit-aer or check your installation.
  RuntimeWarning)
/home/yaelbh/work/terra/System/qiskit/__init__.py:63: RuntimeWarning: Could not import the IBMQ provider from the qiskit-ibmq-provider package. Install qiskit-ibmq-provider or check your installation.
  RuntimeWarning)
/home/yaelbh/.pyxbld/temp.linux-x86_64-3.6/pyrex/qiskit/providers/aer/openpulse/qutip_lite/cy/spmatfuncs.cpp:615:25: fatal error: src/zspmv.hpp: No such file or directory
compilation terminated.
/home/yaelbh/.pyxbld/temp.linux-x86_64-3.6/pyrex/qiskit/providers/aer/openpulse/qutip_lite/cy/spmatfuncs.cpp:615:25: fatal error: src/zspmv.hpp: No such file or directory
compilation terminated.
Traceback (most recent call last):
  File "/opt/anaconda3/envs/YaelEnv/lib/python3.6/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
  File "/opt/anaconda3/envs/YaelEnv/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/opt/anaconda3/envs/YaelEnv/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/opt/anaconda3/envs/YaelEnv/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/anaconda3/envs/YaelEnv/lib/python3.6/site-packages/pyximport/pyximport.py", line 215, in load_module
    inplace=build_inplace, language_level=language_level)
  File "/opt/anaconda3/envs/YaelEnv/lib/python3.6/site-packages/pyximport/pyximport.py", line 191, in build_module
    reload_support=pyxargs.reload_support)
  File "/opt/anaconda3/envs/YaelEnv/lib/python3.6/site-packages/pyximport/pyxbuild.py", line 102, in pyx_to_dll
    dist.run_commands()
  File "/opt/anaconda3/envs/YaelEnv/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/opt/anaconda3/envs/YaelEnv/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/opt/anaconda3/envs/YaelEnv/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/opt/anaconda3/envs/YaelEnv/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/opt/anaconda3/envs/YaelEnv/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 194, in build_extensions
    self.build_extension(ext)
  File "/opt/anaconda3/envs/YaelEnv/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/opt/anaconda3/envs/YaelEnv/lib/python3.6/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/opt/anaconda3/envs/YaelEnv/lib/python3.6/distutils/unixccompiler.py", line 120, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'gcc' failed with exit status 1
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "test/terra/backends/test_qasm_mps_simulator.py", line 18, in <module>
    from test.terra import common
  File "/home/yaelbh/work/aer/MpsVar/test/terra/common.py", line 32, in <module>
    from qiskit.providers.aer import __path__ as main_path
  File "/home/yaelbh/work/aer/MpsVar/qiskit/providers/aer/__init__.py", line 63, in <module>
    from .aerprovider import AerProvider
  File "/home/yaelbh/work/aer/MpsVar/qiskit/providers/aer/aerprovider.py", line 23, in <module>
    from .backends.pulse_simulator import PulseSimulator
  File "/home/yaelbh/work/aer/MpsVar/qiskit/providers/aer/backends/pulse_simulator.py", line 28, in <module>
    from ..openpulse.qobj.digest import digest_pulse_obj
  File "/home/yaelbh/work/aer/MpsVar/qiskit/providers/aer/openpulse/qobj/digest.py", line 25, in <module>
    from .opparse import NoiseParser
  File "/home/yaelbh/work/aer/MpsVar/qiskit/providers/aer/openpulse/qobj/opparse.py", line 22, in <module>
    from .op_qobj import get_func
  File "/home/yaelbh/work/aer/MpsVar/qiskit/providers/aer/openpulse/qobj/op_qobj.py", line 19, in <module>
    from ..qutip_lite import operators as ops
  File "/home/yaelbh/work/aer/MpsVar/qiskit/providers/aer/openpulse/qutip_lite/operators.py", line 612, in <module>
    from .qobj import Qobj
  File "/home/yaelbh/work/aer/MpsVar/qiskit/providers/aer/openpulse/qutip_lite/qobj.py", line 77, in <module>
    from .cy.spmatfuncs import zcsr_mat_elem
  File "/opt/anaconda3/envs/YaelEnv/lib/python3.6/site-packages/pyximport/pyximport.py", line 462, in load_module
    language_level=self.language_level)
  File "/opt/anaconda3/envs/YaelEnv/lib/python3.6/site-packages/pyximport/pyximport.py", line 231, in load_module
    raise exc.with_traceback(tb)
  File "/opt/anaconda3/envs/YaelEnv/lib/python3.6/site-packages/pyximport/pyximport.py", line 215, in load_module
    inplace=build_inplace, language_level=language_level)
  File "/opt/anaconda3/envs/YaelEnv/lib/python3.6/site-packages/pyximport/pyximport.py", line 191, in build_module
    reload_support=pyxargs.reload_support)
  File "/opt/anaconda3/envs/YaelEnv/lib/python3.6/site-packages/pyximport/pyxbuild.py", line 102, in pyx_to_dll
    dist.run_commands()
  File "/opt/anaconda3/envs/YaelEnv/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/opt/anaconda3/envs/YaelEnv/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/opt/anaconda3/envs/YaelEnv/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/opt/anaconda3/envs/YaelEnv/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/opt/anaconda3/envs/YaelEnv/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 194, in build_extensions
    self.build_extension(ext)
  File "/opt/anaconda3/envs/YaelEnv/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/opt/anaconda3/envs/YaelEnv/lib/python3.6/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/opt/anaconda3/envs/YaelEnv/lib/python3.6/distutils/unixccompiler.py", line 120, in _compile
    raise CompileError(msg)
ImportError: Building module qiskit.providers.aer.openpulse.qutip_lite.cy.spmatfuncs failed: ["distutils.errors.CompileError: command 'gcc' failed with exit status 1\n"]
```

**Comment by yaelbh** [comment]
Note that this is Python 3.6

**Comment by yaelbh** [comment]
@nonhermitian comments in Slack: It looks like the Cython files are not being build at install time, and are trying at runtime.  That is what it is telling you.  It however cannot find the sparse matvec header

**Comment by nonhermitian** [comment]
I cannot reproduce this on Ubuntu 18.04.

**Comment by yaelbh** [comment]
It stopped happening at some point.
