### ISSUE TITLE
Using GPU causes Data to not be found

### ISSUE THREAD

**Issue by shreychowdhary** [Qiskit/qiskit-aer#662]
### Informations

- **Qiskit Aer version**: 0.4.1
- **Python version**: 3.6
- **Operating system**: ubuntu

### What is the current behavior?
It throws the following exceptions after running the code for a while:
```
Traceback (most recent call last):
  File "/home/dino/.local/lib/python3.6/site-packages/qiskit/result/result.py", line 265, in _get_experiment
    exp = next(result for result in self.results
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "nvqe.py", line 211, in <module>
    fidelity,energy,iterations = vqe.run()
  File "nvqe.py", line 162, in run
    ret = optimizer.optimize(num_vars=self.num_params, objective_function=self.objective_func, initial_point=self.params)
  File "/home/dino/.local/lib/python3.6/site-packages/qiskit/aqua/components/optimizers/spsa.py", line 139, in optimize
    **self._options)
  File "/home/dino/.local/lib/python3.6/site-packages/qiskit/aqua/components/optimizers/spsa.py", line 190, in _optimization
    cost_plus = obj_fun(theta_plus)
  File "nvqe.py", line 99, in objective_func
    total = self.objective_fun_rec(params,self.N,None)
  File "nvqe.py", line 117, in objective_fun_rec
    total += self.objective_fun_rec(params,N-1,str(i),p)
  File "nvqe.py", line 119, in objective_fun_rec
    total += self.objective_fun_rec(params,N-1,pauli_indexes+str(i),p)
  File "nvqe.py", line 110, in objective_fun_rec
    expected, neg = self.calculate_expected(result.get_counts(qc),pauli_indexes)
  File "/home/dino/.local/lib/python3.6/site-packages/qiskit/result/result.py", line 176, in get_counts
    exp = self._get_experiment(experiment)
  File "/home/dino/.local/lib/python3.6/site-packages/qiskit/result/result.py", line 270, in _get_experiment
    key)
qiskit.exceptions.QiskitError: 'Data for experiment "circuit15860" could not be found. '
```

### Steps to reproduce the problem
[https://gist.github.com/shreychowdhary/beb0bc8c9ad2d2908536a2019b72073f](https://gist.github.com/shreychowdhary/beb0bc8c9ad2d2908536a2019b72073f)
while running using qiskit-aer-gpu

### What is the expected behavior?
Its should run through without any errors which it does if I do not use the statevector_gpu backend option.

### Suggested solutions
None

**Comment by jwoehr** [comment]
My code is using master branch (updated daily, it's 2020-04-15 today) I'm experiencing the same error.
The BasicAer simulators return results.
The Aer statevector gpu simulator and -density matrix gpu simluator both return the error shown by @shreychowdhary due to no results.

**Comment by chriseclectic** [comment]
@jwoehr, are any GPU tests passing for you? (If you have the git repo checked out run `python -m unittest test.terra.backends.test_qasm_simulator_statevector.TestQasmSimulatorStatevectorThrustGPU`)

@hhorii @doichanj Have you been able to look into this yet?

**Comment by jwoehr** [comment]
@chriseclectic I have master branch checked out, yest, but can't get that command to work for me ...  what directory should I be in to execute it?
```
$ python -m unittest test.terra.backends.test_qasm_simulator_statevector.TestQasmSimulatorStatevectorThrustGPU
E
======================================================================
ERROR: terra (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: terra
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
ModuleNotFoundError: No module named 'test.terra'
```

**Comment by hhorii** [comment]
@jwoehr I encountered an error with Aer on Mac that does not have any GPUs. I guess this is not a GPU-specific problem.
```
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/qiskit/result/result.py", line 260, in _get_experiment
    exp = next(result for result in self.results
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "issue_662.py", line 186, in <module>
    vqe.run()
  File "issue_662.py", line 162, in run
    ret = optimizer.optimize(num_vars=self.num_params, objective_function=self.objective_func, initial_point=self.params)
  File "/opt/anaconda3/lib/python3.7/site-packages/qiskit/aqua/components/optimizers/spsa.py", line 126, in optimize
    self._calibration(objective_function, initial_point, num_steps_calibration)
  File "/opt/anaconda3/lib/python3.7/site-packages/qiskit/aqua/components/optimizers/spsa.py", line 237, in _calibration
    obj_plus = obj_fun(theta_plus)
  File "issue_662.py", line 99, in objective_func
    total = self.objective_fun_rec(params,self.N,None)
  File "issue_662.py", line 117, in objective_fun_rec
    total += self.objective_fun_rec(params,N-1,str(i),p)
  File "issue_662.py", line 119, in objective_fun_rec
    total += self.objective_fun_rec(params,N-1,pauli_indexes+str(i),p)
  File "issue_662.py", line 110, in objective_fun_rec
    expected, neg = self.calculate_expected(result.get_counts(qc),pauli_indexes)
  File "/opt/anaconda3/lib/python3.7/site-packages/qiskit/result/result.py", line 175, in get_counts
    exp = self._get_experiment(experiment)
  File "/opt/anaconda3/lib/python3.7/site-packages/qiskit/result/result.py", line 265, in _get_experiment
    key)
qiskit.exceptions.QiskitError: 'Data for experiment "circuit0" could not be found.'
```

**Comment by jwoehr** [comment]
@hhorii I got a notification from you about a similar error on the Mac but I can't find your message here ...

**Comment by chriseclectic** [comment]
@jwoehr That command should be executed in the `qiskit-aer` git repo directory (you may need to have installed in executable mode `pip install -e .` for it to work properly)

**Comment by jwoehr** [comment]
> @jwoehr That command should be executed in the `qiskit-aer` git repo directory (you may need to have installed in executable mode `pip install -e .` for it to work properly)
```
~/work/QISKit/DEV/qiskit-aer$ python -m unittest test.terra.backends.test_qasm_simulator_statevector.TestQasmSimulatorStatevectorThrustGPU
ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss
----------------------------------------------------------------------
Ran 166 tests in 0.007s

OK (skipped=166)
```

**Comment by hhorii** [comment]
GPU simulator may have memory leak.
The `status` of `execute` error was `ERROR: std::bad_alloc: cudaErrorMemoryAllocation: out of memory`.

**Comment by hhorii** [comment]
@jwoehr thank you for your report. I was able to fix it. I believe this fix will be included in the next release (5.2).

**Comment by jwoehr** [comment]
Thank you @hhorii I pull `master` branch daily, I'll watch for your pull request to be accepted!

**Comment by jwoehr** [comment]
I pulled the latest and I don't see any difference in behavior:
```
  File "/home/jax/work/QISKit/qiskit_dev_venv4/lib/python3.6/site-packages/qiskit_terra-0.14.0-py3.6-linux-x86_64.egg/qiskit/result/result.py", line 106, in data
    return self._get_experiment(experiment).data.to_dict()
  File "/home/jax/work/QISKit/qiskit_dev_venv4/lib/python3.6/site-packages/qiskit_terra-0.14.0-py3.6-linux-x86_64.egg/qiskit/result/result.py", line 283, in _get_experiment
    key)
qiskit.exceptions.QiskitError: 'Data for experiment "circuit0" could not be found.'
```
Here's the job dictionary after the run:
```
{   '_args': ({'method': 'density_matrix_gpu'}, None, False),
    '_backend': <QasmSimulator('qasm_simulator') from AerProvider()>,
    '_fn': <bound method AerBackend._run_job of <QasmSimulator('qasm_simulator') from AerProvider()>>,
    '_future': <Future at 0x7f69c9ccaa58 state=finished returned Result>,
    '_job_id': '117d78d5-e76c-47c1-8251-fd38452173c2',
    '_qobj': QasmQobj(qobj_id='9c1b6252-93bf-493c-9838-89035ca2dbb5', config=QasmQobjConfig(backend_options={'method': 'density_matrix_gpu'}, library_dir='/home/jax/work/QISKit/DEV/qiskit-aer/qiskit/providers/aer/backends', max_credits=3, max_memory_mb=3978, memory=True, memory_slots=3, method='density_matrix_gpu', n_qubits=6, parameter_binds=[], shots=1024), experiments=[QasmQobjExperiment(config=QasmQobjExperimentConfig(memory_slots=3, n_qubits=6), header=QobjExperimentHeader(clbit_labels=[['c', 0], ['c', 1], ['c', 2]], creg_sizes=[['c', 3]], memory_slots=3, n_qubits=6, name='circuit0', qreg_sizes=[['q', 6]], qubit_labels=[['q', 0], ['q', 1], ['q', 2], ['q', 3], ['q', 4], ['q', 5]]), instructions=[QasmQobjInstruction(name='h', qubits=[0]), QasmQobjInstruction(name='cx', qubits=[0, 1]), QasmQobjInstruction(name='x', qubits=[0]), QasmQobjInstruction(name='h', qubits=[2]), QasmQobjInstruction(name='cx', qubits=[2, 3]), QasmQobjInstruction(name='x', qubits=[2]), QasmQobjInstruction(name='h', qubits=[4]), QasmQobjInstruction(name='cx', qubits=[4, 5]), QasmQobjInstruction(name='x', qubits=[4]), QasmQobjInstruction(name='barrier', qubits=[0, 1, 2, 3, 4, 5]), QasmQobjInstruction(name='measure', qubits=[1], memory=[0]), QasmQobjInstruction(name='measure', qubits=[3], memory=[1]), QasmQobjInstruction(name='measure', qubits=[5], memory=[2])])], header=QobjHeader(backend_name='qasm_simulator', backend_version='0.6.0'))}
```

**Comment by hhorii** [comment]
@jwoehr Your first error was on `circuit15860`. This means that your 0-15859-th simulation were finished successfully and 15860-th simulation failed.

Your last error was `circuit0`. I believe that your simulator failed without any. Its reason may be that you did not build GPU simulator. 

Could you tell me you specified `-DAER_THRUST_BACKEND=CUDA` or not to build the master?

Ex: `python setup.py bdist_wheel  -- -DAER_THRUST_BACKEND=CUDA -- -j8`

I think you can find a hint of an error reason by checking `result` object )
```
                result = execute(qc, backend, backend_options={"method":"statevector_gpu", "max_parallel_experiments": 16}, shots=NUM_SHOTS).result()
                if (not result.success):
                    print(result)
```

**Comment by jwoehr** [comment]
@hhorii 

> Ex: python setup.py bdist_wheel -- -DAER_THRUST_BACKEND=CUDA -- -j8

Ha! Did not realize I had to do that :)

Where is the build process for Aer GPU documented so I can point the next person who asks me to this step?

**Comment by jwoehr** [comment]
@hhorii build fails on Linux looking for libpthreads
I tried linking libpthread.so to libpthreads.so but that fails as follows:
```
[2/2] Linking C executable cmTC_25cd2
FAILED: cmTC_25cd2
: && /usr/bin/cc -DCMAKE_HAVE_LIBC_PTHREAD   CMakeFiles/cmTC_25cd2.dir/src.c.o  -o cmTC_25cd2   && :
CMakeFiles/cmTC_25cd2.dir/src.c.o: In function `main':
src.c:(.text+0x3e): undefined reference to `pthread_create'
src.c:(.text+0x4a): undefined reference to `pthread_detach'
src.c:(.text+0x5b): undefined reference to `pthread_join'
src.c:(.text+0x6f): undefined reference to `pthread_atfork'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.


Source file was:
#include <pthread.h>

void* test_func(void* data)
{
  return data;
}

int main(void)
{
  pthread_t thread;
  pthread_create(&thread, NULL, test_func, NULL);
  pthread_detach(thread);
  pthread_join(thread, NULL);
  pthread_atfork(NULL, NULL, NULL);
  pthread_exit(NULL);

  return 0;
}
```

**Comment by jwoehr** [comment]
Cmake is not finding libpthread.so ... may need a platform test to add that flag to the cmake configuration for the build. The test code from the configuration as shown in my previous message on this issue compiles fine with `gcc -o foo foo.c -lpthread `... Cmake is just linking it wrong.

**Comment by atilag** [comment]
Ouch, I just find out about this message.
And you are right, the install process is documented but not the build one.
I'll document it!
