### ISSUE TITLE
Aer 0.6.1 does not build on pi4

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-aer#983]
### Informations

- **Qiskit Aer version**: 0.6.1
- **Python version**: 3.7.3
- **Operating system**: Pi

### What is the current behavior?
```
Running cmake-3.18.2.post1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-y9lq6uhw/cmake-3.18.2.post1/egg-dist-tmp-gritru9m
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-y9lq6uhw/cmake-3.18.2.post1/setup.py", line 78, in <module>
    description="Qiskit Aer - High performance simulators for Qiskit",
  File "/home/pi/.local/lib/python3.7/site-packages/skbuild/setuptools_wrap.py", line 437, in setup
    _parse_setuptools_arguments(kw)
  File "/home/pi/.local/lib/python3.7/site-packages/skbuild/setuptools_wrap.py", line 224, in _parse_setuptools_arguments
    for cmd in [dist.get_command_obj(command) for command in dist.commands]:
  File "/home/pi/.local/lib/python3.7/site-packages/skbuild/setuptools_wrap.py", line 224, in <listcomp>
    for cmd in [dist.get_command_obj(command) for command in dist.commands]:
  File "/usr/lib/python3.7/distutils/dist.py", line 858, in get_command_obj
    cmd_obj = self.command_obj[command] = klass(self)
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 163, in __init__
    _Command.__init__(self, dist)
  File "/usr/lib/python3.7/distutils/cmd.py", line 57, in __init__
    raise TypeError("dist must be a Distribution instance")
TypeError: dist must be a Distribution instance
```

### Steps to reproduce the problem
`python3 setup.py install`

**Comment by vvilpas** [comment]
We don't officially support Raspberry Pi but some people have been able to build it. Jan Lahmann fully details the process here: https://medium.com/qiskit/rasqberry-quantum-computing-is-the-coolest-project-for-raspberry-pi-3f64bec5a133.

**Comment by vvilpas** [comment]
I'm closing this one as Raspberry Pi is not officially supported, yet people have been able to build it for that system.
